
Task: Extract Data from a PDF File and convert it into excel file.

Environment: Python 3

Libraries used:
* pandas 
* pdftables
* re



## 1. Introduction
This task requires to read in a pdf file, clean it/wrangle it, make it into a format similar to the one showed in the sample output and finally write the clean data to a csv file.

More details for each task will be given in the following sections.

* importing pdftable library.
* parsing the pdf file 
* examining the data.

In [100]:
from pdftables import get_tables
pdfFile = './health.pdf'
pdfobj = open(pdfFile, 'rb')
tables = get_tables(pdfobj)

for table in tables:
    for row in table:
        print(row)

['TABLE 3. H', 'EA', 'LT', 'H', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '', '', 'I', 'mmuni', 'zation c', 'overage', '(%)', '', '', '', 'Pneumonia', 'Diarrhoea', '', 'Malaria', '']
['', 'Udris', 'se of bnking ervices', 'asic water  (%)', 'Use of bsanitatiservices', 'asic on  (%)', '', '', '', '', '', '', '', '', '', '', 'Protection at birth (PAB) against', 'Care seekingfor children with  symptoms of', 'Treatment with oral rehydra-tion salts', 'Care seeking for children with fever', 'Children sleep-ing under', 'House-holds with at least one']
['Countries', '', '2015', '', '2015', '', 'BCG', 'DTP1β', 'DTP3β', 'polio3', 'MCV1', 'MCV2^', 'HepB3', 'Hib3', 'rota', 'PCV3', 'tetanusλ', '(%)pneumonia', '(ORS) (%)', '(%)', 'ITNs (%)', 'ITN (%)']
['and areas', 'total', 'urban', 'rural', 'totalurban', 'rural', '', '', '', '', '', '2016', '', '', '', '', '', '', '2', '011–2016*', '', '']
['Afghanistan', '63', '89', '53', '3956', '33', '74', '73', '65', '60', '62', '39', '65', '65', '0', '65', '65', '62', '46', '63', '5', '26']
['Albania', '91', '93', '90', '9898', '97', '99', '99', '98', '98', '96', '98', '98', '98', '0', '98', '92', '70x', '54x', '71x', '–', '–']
['Algeria', '93', '95', '89', '8790', '82', '99', '96', '91', '91', '94', '96', '91', '91', '0', '61', '92', '66', '25', '–', '–', '–']
['Andorra', '100', '100', '100', '100100', '100', '–', '99', '98', '98', '97', '90', '94', '98', '0', '92', '–', '–', '–', '–', '–', '–']
['Angola', '41', '63', '23', '3962', '21', '58', '79', '64', '66', '49', '26', '64', '64', '53', '58', '78', '49', '43', '51', '22', '31']
['Anguilla', '98', '98', '–', '9797', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–']
['Antigua and Barbuda', '97', '–', '–', '88–', '–', '–', '99', '99', '86', '98', '87', '99', '99', '0', '0', '–', '–', '–', '–', '–', '–']
['Argentina', '100', '100', '100', '9595', '94', '92', '97', '92', '87', '90', '88', '92', '92', '75', '82', '–', '94', '18', '–', '–', '–']
['Armenia', '99', '99', '99', '9296', '83', '99', '97', '94', '96', '97', '97', '94', '94', '94', '94', '–', '57x', '37', '71', '–', '–']
['Australia', '100', '100', '100', '100–', '–', '–', '98', '94', '94', '95', '94', '94', '94', '87', '94', '–', '–', '–', '–', '–', '–']
['Austria', '100', '100', '100', '100100', '100', '–', '99', '87', '87', '95', '89', '87', '87', '61', '0', '–', '–', '–', '–', '–', '–']
['Azerbaijan', '84', '95', '72', '8992', '87', '98', '98', '97', '98', '98', '98', '97', '97', '0', '97', '–', '36x', '11', '–', '1x', '–']
['Bahamas', '98', '–', '–', '92–', '–', '–', '95', '94', '94', '89', '74', '94', '94', '0', '94', '100', '–', '–', '–', '–', '–']
['Bahrain', '100', '–', '–', '100–', '–', '–', '99', '99', '99', '99', '99', '99', '99', '98', '99', '98', '–', '–', '–', '–', '–']
['Bangladesh', '97', '98', '97', '4754', '43', '99', '99', '97', '97', '94', '93', '97', '97', '0', '97', '97', '42', '77', '55', '–', '–']
['Barbados', '98', '–', '–', '96–', '–', '–', '99', '97', '97', '92', '87', '97', '97', '0', '96', '–', '–', '–', '–', '–', '–']
['Belarus', '98', '98', '99', '9494', '95', '98', '99', '98', '98', '98', '98', '96', '11', '0', '0', '–', '93', '45', '–', '–', '–']
['Belgium', '100', '100', '100', '9999', '99', '–', '99', '98', '98', '96', '85', '97', '97', '87', '94', '–', '–', '–', '–', '–', '–']
['Belize', '97', '99', '96', '8791', '84', '94', '98', '95', '96', '95', '96', '95', '95', '0', '0', '91', '67', '55', '71', '–', '–']
['Benin', '67', '77', '60', '1425', '5', '96', '86', '82', '78', '74', '0', '82', '82', '0', '75', '85', '23', '25', '44', '73', '77']
['Bhutan', '98', '97', '98', '6372', '57', '99', '99', '98', '97', '97', '90', '98', '98', '0', '0', '89', '74x', '61x', '–', '–', '–']
['Bolivia (Plurinational State of)', '93', '99', '79', '5364', '27', '99', '99', '99', '99', '99', '0', '99', '99', '99', '97', '87', '62', '22', '–', '–', '–']
['Bosnia and Herzegovina', '98', '97', '98', '9599', '92', '97', '90', '78', '79', '83', '78', '78', '69', '0', '0', '–', '87', '36', '–', '–', '–']
['Botswana', '79', '95', '58', '6075', '39', '98', '98', '95', '96', '97', '74', '95', '95', '95', '95', '92', '14x', '43x', '75x', '31', '53']
['Brazil', '97', '99', '87', '8691', '58', '99', '89', '86', '98', '96', '72', '86', '86', '94', '94', '93', '50x', '–', '–', '–', '–']
['British Virgin Islands', '100', '–', '–', '97–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–']
['Brunei Darussalam', '100', '100', '99', '9696', '97', '99', '99', '99', '99', '98', '97', '99', '99', '0', '0', '95', '–', '–', '–', '–', '–']
['Bulgaria', '99', '99', '99', '8687', '84', '96', '94', '92', '92', '92', '88', '91', '92', '0', '90', '–', '–', '–', '–', '–', '–']
['Burkina Faso', '54', '79', '43', '2348', '12', '98', '95', '91', '91', '88', '50', '91', '91', '91', '91', '92', '52', '40', '61', '75', '90']
['Burundi', '56', '88', '52', '5046', '51', '93', '97', '94', '94', '93', '72', '94', '94', '96', '94', '85', '63', '36', '69', '40', '46']
['Cabo Verde', '86', '93', '74', '6573', '51', '96', '96', '96', '95', '92', '95', '96', '96', '0', '0', '92', '–', '–', '–', '–', '–']
['Cambodia', '75', '96', '70', '4988', '39', '97', '92', '90', '87', '81', '58', '90', '90', '0', '87', '93', '69', '35', '61', '4x', '5x']
['Cameroon', '65', '84', '43', '3956', '19', '70', '92', '85', '83', '78', '0', '85', '85', '80', '84', '85', '28', '16', '33', '55', '71']
['Canada', '99', '–', '–', '99–', '–', '–', '96', '91', '91', '90', '86', '55', '91', '0', '79', '–', '–', '–', '–', '–', '–']
['Central African Republic', '54', '74', '41', '2549', '9', '74', '69', '47', '47', '49', '0', '47', '47', '0', '47', '60', '30x', '16x', '–', '36x', '47x']
['Chad', '43', '78', '32', '1033', '3', '56', '60', '46', '44', '58', '0', '46', '46', '0', '0', '80', '26', '20', '23', '36', '77']
['Chile', '100', '100', '100', '100100', '99', '97', '99', '95', '95', '93', '87', '95', '95', '0', '90', '–', '–', '–', '–', '–', '–']
['China', '96', '96', '96', '7586', '61', '99', '99', '99', '99', '99', '99', '99', '0', '0', '0', '–', '–', '–', '–', '–', '–']
['Colombia', '97', '100', '86', '8488', '72', '88', '93', '91', '91', '93', '87', '91', '91', '90', '89', '90', '64x', '54x', '54x', '–', '3x']
['Comoros', '84', '93', '80', '3447', '29', '94', '96', '91', '92', '99', '0', '91', '91', '0', '0', '85', '38', '38', '45', '41', '59']
['Congo', '68', '85', '37', '1520', '6', '85', '85', '80', '80', '80', '0', '80', '80', '80', '80', '85', '28', '28', '51', '61', '66']
['Cook Islands', '100', '–', '–', '98–', '–', '99', '99', '99', '99', '90', '90', '99', '99', '0', '0', '–', '–', '–', '–', '–', '–']
['Costa Rica', '100', '100', '100', '9798', '94', '89', '99', '97', '97', '93', '87', '97', '97', '0', '94', '–', '77', '40', '–', '–', '–']
["Côte d'Ivoire", '73', '89', '54', '3045', '13', '95', '98', '85', '80', '77', '0', '85', '85', '0', '83', '90', '38', '17', '43', '37', '67']
['Croatia', '100', '100', '100', '9798', '96', '99', '98', '93', '93', '90', '96', '93', '93', '0', '0', '–', '–', '–', '–', '–', '–']
['Cuba', '95', '97', '90', '9192', '88', '99', '99', '99', '98', '99', '99', '99', '99', '0', '0', '–', '93', '61', '93', '–', '–']
['Cyprus', '100', '100', '100', '99100', '99', '–', '98', '97', '97', '90', '88', '97', '96', '0', '81', '–', '–', '–', '–', '–', '–']
['Czechia', '100', '100', '100', '9999', '99', '–', '98', '96', '96', '98', '93', '96', '96', '0', '0', '–', '–', '–', '–', '–', '–']
["Democratic People's Republic of Korea", '100', '100', '99', '7783', '68', '97', '97', '96', '99', '99', '98', '96', '96', '0', '0', '97', '80x', '74x', '–', '–', '–']
['Democratic Republic of the Congo', '42', '70', '21', '2023', '18', '80', '80', '79', '74', '77', '0', '79', '79', '0', '77', '85', '42', '39', '55', '56', '70']
['Denmark', '100', '100', '100', '100100', '100', '–', '97', '94', '94', '94', '85', '0', '94', '0', '94', '–', '–', '–', '–', '–', '–']
['Djibouti', '77', '83', '55', '5163', '13', '90', '90', '84', '84', '75', '82', '84', '84', '86', '82', '85', '94', '94', '–', '20x', '32']
['Dominica', '97', '–', '–', '78–', '–', '98', '99', '99', '99', '96', '92', '99', '99', '0', '0', '–', '–', '–', '–', '–', '–']
['Dominican Republic', '94', '97', '86', '8385', '74', '99', '98', '87', '82', '85', '0', '80', '73', '75', '30', '90', '73', '48', '65', '–', '–']
['Ecuador', '93', '100', '80', '8689', '80', '84', '94', '83', '79', '86', '76', '84', '84', '80', '84', '88', '–', '46', '–', '–', '–']
['Egypt', '98', '99', '98', '9397', '90', '96', '96', '95', '95', '95', '96', '95', '95', '0', '0', '80', '68', '28', '68', '–', '–']
['El Salvador', '93', '98', '83', '9193', '87', '99', '97', '93', '95', '90', '87', '93', '93', '93', '90', '90', '80', '70', '–', '–', '–']
['Equatorial Guinea', '50', '78', '31', '7580', '71', '48', '40', '19', '20', '30', '0', '19', '19', '0', '0', '70', '54', '40', '62', '23', '38']
['Eritrea', '19', '66', '6', '1129', '6', '97', '97', '95', '95', '93', '85', '95', '95', '96', '95', '94', '45x', '43x', '–', '20x', '71x']
['Estonia', '100', '100', '99', '100100', '100', '95', '94', '93', '93', '93', '92', '93', '93', '85', '0', '–', '–', '–', '–', '–', '–']
['Ethiopia', '39', '77', '30', '718', '4', '75', '86', '77', '75', '70', '0', '77', '77', '63', '76', '80', '30', '30', '35', '45', '64']
['Fiji', '94', '98', '89', '9696', '95', '99', '99', '99', '99', '94', '94', '99', '99', '99', '99', '94', '–', '–', '–', '–', '–']
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['TABLE 3. HEALTH', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '', '', 'I', 'mmuni', 'zation c', 'overag', 'e (%)', '', '', '', 'Pneumonia', 'Diarrhoea', '', 'Malaria', '']
['', 'Udris', 'se of bnking ervices', 'asic water  (%)', 'Usse', 'se of basic anitation rvices (%)', '', '', '', '', '', '', '', '', '', '', 'Protection at birth (PAB) against', 'Care seekingfor children with  symptoms of', 'Treatment with oral rehydra-tion salts', 'Care seeking for children with fever', 'Childrensleep-ing under', 'House-holds with at least one']
['Countries', '', '2015', '', '', '2015', 'BCG', 'DTP1β', 'DTP3β', 'polio3', 'MCV1', 'MCV2^', 'HepB3', 'Hib3', 'rota', 'PCV3', 'tetanusλ', '(%)pneumonia', '(ORS) (%)', '(%)', 'ITNs (%)', 'ITN (%)']
['and areas', 'tota', 'lurban', 'rural', 'total', 'urbanrural', '', '', '', '', '', '2016', '', '', '', '', '', '', '2', '011–2016*', '', '']
['Finland', '100', '100', '100', '99', '9999', '–', '99', '92', '92', '94', '85', '0', '92', '84', '87', '–', '–', '–', '–', '–', '–']
['France', '100', '100', '100', '99', '9999', '–', '99', '97', '97', '90', '79', '88', '96', '0', '91', '–', '–', '–', '–', '–', '–']
['Gabon', '88', '92', '59', '41', '4232', '94', '83', '75', '74', '64', '0', '75', '75', '0', '0', '90', '68', '26', '67', '39', '36']
['Gambia', '80', '88', '68', '42', '4635', '98', '99', '95', '95', '97', '79', '95', '95', '95', '95', '92', '68', '59', '65', '47', '69']
['Georgia', '93', '98', '87', '85', '9573', '98', '97', '92', '92', '93', '85', '92', '92', '75', '75', '–', '74x', '40x', '–', '–', '–']
['Germany', '100', '100', '100', '99', '9999', '–', '95', '95', '94', '97', '93', '88', '93', '66', '86', '–', '–', '–', '–', '–', '–']
['Ghana', '78', '88', '66', '14', '199', '94', '94', '93', '95', '89', '75', '93', '93', '94', '93', '88', '56', '49', '77', '47', '68']
['Greece', '100', '100', '100', '99', '9998', '–', '99', '99', '99', '97', '83', '96', '99', '20', '96', '–', '–', '–', '–', '–', '–']
['Grenada', '96', '–', '–', '78', '––', '–', '98', '96', '98', '95', '85', '96', '96', '0', '0', '–', '–', '–', '–', '–', '–']
['Guatemala', '94', '97', '89', '67', '8153', '87', '96', '80', '82', '86', '65', '80', '80', '82', '81', '90', '52', '49', '50', '–', '–']
['Guinea', '67', '88', '55', '22', '3415', '72', '65', '57', '42', '54', '0', '57', '57', '0', '0', '80', '37', '34', '37', '26', '47']
['Guinea-Bissau', '69', '85', '54', '21', '358', '94', '95', '87', '87', '81', '0', '87', '87', '61', '80', '80', '34', '35', '51', '81', '90']
['Guyana', '95', '100', '93', '86', '8985', '95', '97', '97', '94', '99', '94', '97', '97', '96', '92', '99', '84', '43', '71', '7', '5']
['Haiti', '64', '81', '40', '31', '3722', '72', '78', '58', '56', '53', '26', '58', '58', '48', '0', '88', '38', '53', '40', '12', '19']
['Holy See', '–', '–', '–', '–', '––', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–']
['Honduras', '92', '99', '84', '80', '8475', '99', '99', '97', '97', '88', '0', '97', '97', '97', '97', '94', '64', '60', '62', '–', '–']
['Hungary', '100', '100', '100', '98', '9899', '99', '99', '99', '99', '99', '99', '0', '99', '0', '98', '–', '–', '–', '–', '–', '–']
['Iceland', '100', '100', '100', '99', '99100', '–', '96', '91', '91', '91', '95', '0', '91', '0', '90', '–', '–', '–', '–', '–', '–']
['India', '88', '93', '85', '44', '6534', '89', '91', '88', '86', '88', '76', '88', '80', '4', '0', '87', '73', '51', '71x', '–', '–']
['Indonesia', '90', '97', '81', '68', '7757', '81', '95', '79', '80', '76', '56', '79', '79', '0', '0', '85', '75', '39', '74', '3x', '3x']
['Iran (Islamic Republic of)', '95', '97', '89', '88', '9279', '99', '99', '99', '99', '99', '98', '99', '99', '0', '0', '95', '76x', '61x', '–', '–', '–']
['Iraq', '86', '90', '78', '86', '8686', '94', '73', '63', '68', '66', '64', '61', '63', '34', '0', '75', '74', '23', '–', '–', '–']
['Ireland', '99', '99', '99', '92', '9195', '18', '98', '95', '95', '92', '0', '95', '95', '0', '91', '–', '–', '–', '–', '–', '–']
['Israel', '100', '100', '100', '100', '100100', '–', '94', '94', '94', '97', '97', '95', '94', '81', '93', '–', '–', '–', '–', '–', '–']
['Italy', '100', '100', '100', '99', '9999', '–', '97', '93', '93', '85', '83', '93', '93', '0', '89', '–', '–', '–', '–', '–', '–']
['Jamaica', '93', '97', '88', '85', '8487', '96', '99', '99', '99', '95', '85', '98', '99', '0', '0', '80', '82', '64', '–', '–', '–']
['Japan', '99', '–', '–', '100', '––', '84', '99', '99', '99', '96', '93', '0', '99', '0', '99', '–', '–', '–', '–', '–', '–']
['Jordan', '99', '99', '97', '97', '9796', '99', '99', '98', '98', '96', '99', '98', '98', '97', '0', '90', '77', '20', '69', '–', '–']
['Kazakhstan', '91', '97', '84', '98', '9799', '95', '93', '82', '82', '99', '99', '82', '82', '0', '97', '–', '81', '62', '–', '–', '–']
['Kenya', '58', '83', '50', '30', '3528', '99', '96', '89', '88', '75', '32', '89', '89', '74', '78', '85', '66', '54', '72', '56', '59']
['Kiribati', '64', '90', '44', '40', '4932', '79', '82', '81', '82', '80', '79', '81', '81', '79', '79', '90', '81x', '62x', '27x', '–', '–']
['Kuwait', '100', '–', '–', '100', '––', '99', '99', '99', '99', '93', '96', '99', '99', '0', '99', '95', '–', '–', '–', '–', '–']
['Kyrgyzstan', '87', '97', '82', '97', '9399', '97', '97', '96', '97', '97', '98', '96', '96', '0', '0', '–', '60', '33', '56', '–', '–']
["Lao People's Democratic Republic", '80', '92', '73', '73', '9360', '78', '85', '82', '83', '76', '0', '82', '82', '0', '78', '90', '54', '42', '–', '43', '50']
['Latvia', '99', '99', '98', '93', '9784', '96', '99', '98', '98', '93', '89', '98', '98', '83', '82', '–', '–', '–', '–', '–', '–']
['Lebanon', '92', '–', '–', '95', '––', '–', '84', '81', '75', '79', '75', '81', '81', '0', '0', '–', '74x', '44x', '–', '–', '–']
['Lesotho', '72', '87', '66', '44', '4643', '98', '98', '93', '90', '90', '82', '93', '93', '0', '93', '85', '63', '53', '61', '–', '–']
['Liberia', '70', '80', '60', '17', '286', '97', '99', '79', '79', '80', '0', '79', '79', '48', '79', '89', '51', '60', '78', '44', '62']
['Libya', '97', '–', '–', '100', '––', '99', '98', '97', '97', '97', '96', '97', '97', '97', '96', '–', '–', '–', '–', '–', '–']
['Liechtenstein', '100', '–', '–', '100', '––', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–']
['Lithuania', '97', '100', '93', '94', '9786', '98', '97', '94', '94', '94', '92', '95', '94', '0', '82', '–', '–', '–', '–', '–', '–']
['Luxembourg', '100', '100', '100', '98', '9799', '–', '99', '99', '99', '99', '86', '94', '99', '89', '95', '–', '–', '–', '–', '–', '–']
['Madagascar', '51', '82', '34', '10', '166', '70', '84', '77', '75', '58', '0', '77', '77', '78', '76', '78', '41', '15', '46', '73', '80']
['Malawi', '67', '87', '63', '44', '4943', '86', '89', '84', '83', '81', '61', '84', '84', '81', '83', '89', '78', '65', '67', '43', '57']
['Malaysia', '96', '99', '89', '100', '10099', '98', '99', '98', '98', '96', '99', '98', '98', '0', '0', '90', '–', '–', '–', '–', '–']
['Maldives', '98', '96', '100', '96', '9398', '99', '99', '99', '99', '99', '99', '99', '99', '0', '0', '99', '22x', '57x', '84x', '–', '–']
['Mali', '74', '91', '63', '31', '4622', '92', '86', '68', '67', '75', '0', '68', '68', '60', '70', '85', '23', '22x', '49', '79', '93']
['Malta', '100', '100', '100', '100', '100100', '–', '97', '97', '97', '93', '86', '97', '97', '0', '0', '–', '–', '–', '–', '–', '–']
['Marshall Islands', '78', '70', '99', '87', '9566', '94', '87', '71', '69', '75', '49', '73', '58', '38', '51', '–', '–', '38x', '63x', '–', '–']
['Mauritania', '70', '86', '45', '45', '6317', '85', '87', '73', '67', '70', '0', '73', '73', '73', '73', '80', '34', '19', '35', '18', '67']
['Mauritius', '100', '100', '100', '93', '9493', '98', '97', '96', '96', '92', '92', '72', '96', '92', '10', '95', '–', '–', '–', '–', '–']
['Mexico', '98', '100', '94', '89', '9181', '99', '99', '97', '96', '96', '98', '93', '97', '72', '92', '90', '73', '61', '–', '–', '–']
['Micronesia (Federated States of)', '88', '97', '86', '–', '––', '85', '95', '69', '68', '70', '74', '76', '61', '46', '63', '–', '–', '–', '–', '–', '–']
['Monaco', '100', '100', '–', '100', '100–', '89', '99', '99', '99', '99', '0', '99', '99', '0', '0', '–', '–', '–', '–', '–', '–']
['Mongolia', '83', '94', '56', '59', '6641', '99', '99', '99', '99', '98', '90', '99', '99', '0', '0', '–', '70', '42', '–', '–', '–']
['Montenegro', '98', '97', '99', '96', '9892', '88', '97', '89', '89', '47', '86', '75', '89', '0', '0', '–', '89x', '16x', '74', '–', '–']
['Montserrat', '97', '–', '–', '89', '––', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–']
['Morocco', '83', '96', '64', '83', '8975', '99', '99', '99', '99', '99', '99', '99', '99', '99', '98', '90', '70', '22', '–', '–', '–']
['Mozambique', '47', '79', '32', '24', '4712', '95', '90', '80', '80', '91', '51', '80', '80', '76', '80', '83', '50', '55', '56', '36', '51']
['Myanmar', '68', '82', '60', '65', '7659', '88', '94', '90', '89', '91', '86', '90', '90', '0', '14', '87', '58', '62', '65', '19', '27']
['Namibia', '79', '97', '63', '34', '5515', '94', '98', '92', '92', '85', '0', '92', '92', '86', '81', '88', '68', '72', '63', '6', '24']
['Nauru', '100', '100', '–', '66', '66–', '99', '98', '91', '91', '98', '96', '91', '91', '0', '0', '–', '69x', '23x', '51x', '–', '–']
['Nepal', '88', '89', '87', '46', '5245', '93', '92', '87', '85', '83', '25', '87', '87', '0', '46', '82', '85', '37', '46', '–', '–']
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['TABLE 3. HEALTH', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '', '', 'I', 'mmuni', 'zation c', 'overage', '(%)', '', '', '', 'Pneumonia', 'Diarrhoea', '', 'Malaria', '']

* upon investigating the data I found that the countries before Uganda follow a different pattern to the countries after that.
* so we decided to split this task into 2 steps, step 1 was to examine and clean the data set before uganda and later to deal with countries after.
* as seen in the previous task, I like to create list to examine and clean the data and then add that list a column of the data frame.
* I found that each country had 21 columns associated to it, so i needed to create 22 list (one for the country and 21 for the assoiciated values.

In [101]:
import pandas as pd
country=[]
col_1=[]
col_2=[]
col_3=[]
col_4=[]
col_5=[]
col_6=[]
col_7=[]
col_8=[]
col_9=[]
col_10=[]
col_11=[]
col_12=[]
col_13=[]
col_14=[]
col_15=[]
col_16=[]
col_17=[]
col_18=[]
col_19=[]
col_20=[]
col_21=[]

for table in tables:
    for row in table[5:]:
        if(row[0]=='Uganda397332'):
            break
        country.append(row[0])
        col_1.append(row[1])
        col_2.append(row[2])
        col_3.append(row[3])
        col_4.append(row[4])
        col_5.append(row[5])
        col_6.append(row[6])
        col_7.append(row[7])
        col_8.append(row[8])
        col_9.append(row[9])
        col_10.append(row[10])
        col_11.append(row[11])
        col_12.append(row[12])
        col_13.append(row[13])
        col_14.append(row[14])
        col_15.append(row[15])
        col_16.append(row[16])
        col_17.append(row[17])
        col_18.append(row[18])
        col_19.append(row[19])
        col_20.append(row[20])
        col_21.append(row[21])

* Now I create a data frame and add the diffrent list to the associated columns.
* later, we rearrange the columns.

In [102]:
df=pd.DataFrame({'Country Name':country,'0':col_1,'1':col_2,'2':col_3,'3':col_4,'5':col_5,'6':col_6,'7':col_7,'8':col_8,'9':col_9,'10':col_10,'11':col_11,'12':col_12,'13':col_13,'14':col_14,'15':col_15,'16':col_16,'17':col_17,'18':col_18,'19':col_19,'20':col_20,'21':col_21})
cols = list(df.columns.values)
print(cols)
df = df[['Country Name', '0', '1', '2', '3','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21']]
df.head()

['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '3', '5', '6', '7', '8', '9', 'Country Name']

,Country Name,0,1,2,3,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,Afghanistan,63,89,53,3956,33,74,73,65,60,...,65,65,0,65,65,62,46,63,5,26
1,Albania,91,93,90,9898,97,99,99,98,98,...,98,98,0,98,92,70x,54x,71x,–,–
2,Algeria,93,95,89,8790,82,99,96,91,91,...,91,91,0,61,92,66,25,–,–,–
3,Andorra,100,100,100,100100,100,–,99,98,98,...,94,98,0,92,–,–,–,–,–,–
4,Angola,41,63,23,3962,21,58,79,64,66,...,64,64,53,58,78,49,43,51,22,31

* Now that we have the data in a dataframe it is now time to wrangle all the data.
* we can see that there are a few columns that have merged values, first one is the column labelled 3.
* Lets investigate this.

In [103]:
for items in df['3']:
    print(items)

3956
9898
8790
100100
3962
9797
88–
9595
9296
100–
100100
8992
92–
100–
4754
96–
9494
9999
8791
1425
6372
5364
9599
6075
8691
97–
9696
8687
2348
5046
6573
4988
3956
99–
2549
1033
100100
7586
8488
3447
1520
98–
9798
3045
9798
9192
99100
9999
7783
2023
100100
5163
78–
8385
8689
9397
9193
7580
1129
100100
718
9696


99
99
41
42
85
99
14
99
78
67
22
21
86
31
–
80
98
99
44
68
88
86
92
100
99
85
100
97
98
30
40
100
97
73
93
95
44
17
100
100
94
98
10
44
100
96
31
100
87
45
93
89
–
100
59
96
89
83
24
65
34
66
46


9898
100100
7686
1344
3339
97–
9898
9999
5874
100100
7786
1955
9198
7782
7579
9898
9999
100–
100–
7889
8293
8993
6257
––
9186
87–
9798
100–
4047
100–
4866
9598
100–
1524
100100
9999
9999
3176
1628
7376
1028
100100
9489
9695
3558
7988
5858
9999
100100
9396
9594
9594
9197
4473
1428
93–
9397
92–
9398
9699
9794
88–
9192

* investigating the column labelled 3, I found that it has 2 columns merged into it and each item has different lengths.
* I also found out that column labeled 5 has some merged values too, but we shall investigate this later.
* we shall break and create the first colum out of the merged column.
* we will create a list first, examine different lengths of items in the column 3 and 5, match values againist pdf and create conditions to correctly append these values to the list and later we shall add the list to our data frame.

In [104]:
theCol=[]

i=0
for items in df['3']:
    if (len(items)==5):
        theCol.append(items[0:2])
        
    elif (len(items)==4 and items[3]!='–'):
        theCol.append(items[0:2])  
        
    elif(items=='100–'):
        theCol.append(items[0:3])
        
    elif (len(items)==3 and items[2]=='–'):
        theCol.append(items[0:2])
        
    elif (len(items)==3 and items!='100' and items[2]!='–' ):
        theCol.append(items[0])
        
    elif (len(items)==3 and items=='100'):
        theCol.append(items)
        
    elif(len(items)==2 and items!='––'):
        theCol.append(items)
        
    elif(items=='––'):
        theCol.append(items[0])
    elif(items=='718'):
        theCol.append(items[0])
        
    elif(len(items)==1):
        theCol.append(items)
    else:
        theCol.append(items[0:3])   

#Checking if the list has correct amount of items as the dataframe.
print(len(theCol))

#adding the list to the dataframe.
df['test']=theCol
df=df[df['3'] != '']
df.reset_index(drop=True, inplace= True)
df.head()

194

,Country Name,0,1,2,3,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,test
0,Afghanistan,63,89,53,3956,33,74,73,65,60,...,65,0,65,65,62,46,63,5,26,39
1,Albania,91,93,90,9898,97,99,99,98,98,...,98,0,98,92,70x,54x,71x,–,–,98
2,Algeria,93,95,89,8790,82,99,96,91,91,...,91,0,61,92,66,25,–,–,–,87
3,Andorra,100,100,100,100100,100,–,99,98,98,...,98,0,92,–,–,–,–,–,–,100
4,Angola,41,63,23,3962,21,58,79,64,66,...,64,53,58,78,49,43,51,22,31,39

* lets now do the same thing as we did for the column 3 previously but now for the other merged column.

In [105]:
theCol_1=[]
for items in df['3']:
    
    if (len(items)==1):
        theCol_1.append('')
        
    elif(len(items)==2 and items!='––'):
        theCol_1.append('')
        
    elif (items=='––'):
        theCol_1.append(items[0])
    elif (items=='718'):
        theCol_1.append(items[1:3])
        
    elif(len(items)==3 and items!='100'):
        theCol_1.append(items[2])
        
    elif(items=='100'):
        theCol_1.append('')
        
    elif (len(items)==4 and items!='100–'):
        theCol_1.append(items[-2:])
        
    elif(items=='100–'):
        theCol_1.append(items[3])
        
    else:
        theCol_1.append(items[-3:])
    
print(len(theCol_1))
df['test 1']=theCol_1
df

188

,Country Name,0,1,2,3,5,6,7,8,9,...,14,15,16,17,18,19,20,21,test,test 1
0,Afghanistan,63,89,53,3956,33,74,73,65,60,...,0,65,65,62,46,63,5,26,39,56
1,Albania,91,93,90,9898,97,99,99,98,98,...,0,98,92,70x,54x,71x,–,–,98,98
2,Algeria,93,95,89,8790,82,99,96,91,91,...,0,61,92,66,25,–,–,–,87,90
3,Andorra,100,100,100,100100,100,–,99,98,98,...,0,92,–,–,–,–,–,–,100,100
4,Angola,41,63,23,3962,21,58,79,64,66,...,53,58,78,49,43,51,22,31,39,62
5,Anguilla,98,98,–,9797,–,–,–,–,–,...,–,–,–,–,–,–,–,–,97,97
6,Antigua and Barbuda,97,–,–,88–,–,–,99,99,86,...,0,0,–,–,–,–,–,–,88,–
7,Argentina,100,100,100,9595,94,92,97,92,87,...,75,82,–,94,18,–,–,–,95,95
8,Armenia,99,99,99,9296,83,99,97,94,96,...,94,94,–,57x,37,71,–,–,92,96
9,Australia,100,100,100,100–,–,–,98,94,94,...,87,94,–,–,–,–,–,–,100,–
10,Austria,100,100,100,100100,100,–,99,87,87,...,61,0,–,–,–,–,–,–,100,100
11,Azerbaijan,84,95,72,8992,87,98,98,97,98,...,0,97,–,36x,11,–,1x,–,89,92
12,Bahamas,98,–,–,92–,–,–,95,94,94,...,0,94,100,–,–,–,–,–,92,–
13,Bahrain,100,–,–,100–,–,–,99,99,99,...,98,99,98,–,–,–,–,–,100,–
14,Bangladesh,97,98,97,4754,43,99,99,97,97,...,0,97,97,42,77,55,–,–,47,54
15,Barbados,98,–,–,96–,–,–,99,97,97,...,0,96,–,–,–,–,–,–,96,–
16,Belarus,98,98,99,9494,95,98,99,98,98,...,0,0,–,93,45,–,–,–,94,94
17,Belgium,100,100,100,9999,99,–,99,98,98,...,87,94,–,–,–,–,–,–,99,99
18,Belize,97,99,96,8791,84,94,98,95,96,...,0,0,91,67,55,71,–,–,87,91
19,Benin,67,77,60,1425,5,96,86,82,78,...,0,75,85,23,25,44,73,77,14,25
20,Bhutan,98,97,98,6372,57,99,99,98,97,...,0,0,89,74x,61x,–,–,–,63,72
21,Bolivia (Plurinational State of),93,99,79,5364,27,99,99,99,99,...,99,97,87,62,22,–,–,–,53,64
22,Bosnia and Herzegovina,98,97,98,9599,92,97,90,78,79,...,0,0,–,87,36,–,–,–,95,99
23,Botswana,79,95,58,6075,39,98,98,95,96,...,95,95,92,14x,43x,75x,31,53,60,75
24,Brazil,97,99,87,8691,58,99,89,86,98,...,94,94,93,50x,–,–,–,–,86,91
25,British Virgin Islands,100,–,–,97–,–,–,–,–,–,...,–,–,–,–,–,–,–,–,97,–
26,Brunei Darussalam,100,100,99,9696,97,99,99,99,99,...,0,0,95,–,–,–,–,–,96,96
27,Bulgaria,99,99,99,8687,84,96,94,92,92,...,0,90,–,–,–,–,–,–,86,87
28,Burkina Faso,54,79,43,2348,12,98,95,91,91,...,91,91,92,52,40,61,75,90,23,48
29,Burundi,56,88,52,5046,51,93,97,94,94,...,96,94,85,63,36,69,40,46,50,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,Sierra Leone,58,75,47,1524,8,92,97,84,84,...,95,84,90,72,85,72,49,64,15,24
159,Singapore,100,100,–,100100,–,99,98,97,96,...,57,78,–,–,–,–,–,–,100,100
160,Slovakia,98,99,97,9999,98,0,99,96,96,...,0,96,–,–,–,–,–,–,99,99
161,Slovenia,100,100,99,9999,99,–,98,94,94,...,0,50,–,–,–,–,–,–,99,99
162,Solomon Islands,64,90,56,3176,18,98,99,99,99,...,0,87,85,79,37,61,70,86,31,76
163,Somalia,40,70,20,1628,8,37,52,42,47,...,0,0,67,13x,13x,–,11x,12x,16,28
164,South Africa,85,97,63,7376,69,74,78,66,66,...,73,69,80,88,51,68,–,–,73,76
165,South Sudan,50,60,48,1028,6,37,35,26,31,...,0,0,75,48x,39x,57,46,66,10,28
166,Spain,100,100,100,100100,100,–,99,97,97,...,0,0,–,–,–,–,–,–,100,100
167,Sri Lanka,92,96,91,9489,95,99,99,99,99,...,0,0,95,58x,51x,85x,3x,5x,94,89
168,State of Palestine,88,86,94,9695,99,99,99,99,99,...,0,99,–,77,32,–,–,–,96,95
169,Sudan,59,73,52,3558,23,96,97,93,93,...,90,93,77,48,20,–,30x,25x,35,58
170,Suriname,95,98,88,7988,61,–,92,91,91,...,0,0,93,76x,42x,–,43x,61x,79,88
171,Swaziland,68,95,60,5858,58,97,96,90,90,...,95,90,90,60,84,63,2x,10x,58,58
172,Sweden,100,100,100,9999,100,26,99,98,98,...,0,97,–,–,–,–,–,–,99,99
173,Switzerland,100,100,100,100100,100,–,99,97,97,...,0,81,–,–,–,–,–,–,100,100
174,Syrian Arab Republic,97,99,94,9396,89,66,61,42,48,...,0,0,91,77x,50x,–,–,–,93,96
175,Tajikistan,74,92,68,9594,96,98,98,96,97,...,96,0,–,63,60,57,1x,2x,95,94
176,Thailand,98,99,97,9594,96,99,99,99,99,...,0,0,95,80,73,76,–,–,95,94
177,The former Yugoslav Republic of Macedonia,97,96,98,9197,83,99,97,95,95,...,0,0,–,93x,62,–,–,–,91,97
178,Timor-Leste,70,91,60,4473,30,85,95,85,83,...,0,0,81,71x,71x,73x,41x,41x,44,73
179,Togo,63,90,45,1428,5,79,93,89,89,...,90,89,83,49,19,58,43,65,14,28
180,Tokelau,100,–,100,93–,93,–,–,–,–,...,–,–,–,–,–,–,–,–,93,–
181,Tonga,100,100,100,9397,92,80,83,78,80,...,0,0,–,–,–,64,–,–,93,97
182,Trinidad and Tobago,97,–,–,92–,–,–,97,97,84,...,0,91,–,74x,–,–,–,–,92,–
183,Tunisia,94,100,83,9398,83,95,99,98,98,...,0,0,96,60,65,–,–,–,93,98
184,Turkey,99,99,100,9699,89,96,99,98,98,...,0,98,90,–,–,–,–,–,96,99
185,Turkmenistan,94,91,98,9794,99,98,99,98,98,...,0,0,–,59,47,–,–,–,97,94
186,Turks and Caicos Islands,94,–,–,88–,–,–,–,–,–,...,–,–,–,–,–,–,–,–,88,–
187,Tuvalu,99,100,99,9192,91,98,99,94,94,...,0,0,–,–,44x,79x,–,–,91,92

* we have thus far dealt with merged column 3, split these to columns called test and test 1.
* our analysis brings us to column 5 now. 
* as seen with column 3 we shall use the same approach ie examine the data and fix all the merged columns.

In [106]:
for items in df['5']:
    print(items)

33
97
82
100
21
–
–
94
83
–
100
87
–
–
43
–
95
99
84
5
57
27
92
39
58
–
97
84
12
51
51
39
19
–
9
3
99
61
72
29
6
–
94
13
96
88
99
99
68
18
100
13
–
74
80
90
87
71
6
100
4
95
9999
9999
4232
4635
9573
9999
199
9998
––
8153
3415
358
8985
3722
––
8475
9899
99100
6534
7757
9279
8686
9195
100100
9999
8487
––
9796
9799
3528
4932
––
9399
9360
9784
––
4643
286
––
––
9786
9799
166
4943
10099
9398
4622
100100
9566
6317
9493
9181
––
100–
6641
9892
––
8975
4712
7659
5515
66–
5245
100
100
63
6
27
–
98
99
48
100
59
13
81
58
72
98
100
–
–
70
68
76
64
–
92
–
96
–
28
–
35
91
–
8
–
98
99
18
8
69
6
100
95
99
23
61
58
100
100
89
96
96
83
30
5
93
92
–
83
89
99
–
91

In [107]:
theColumn=[]
for items in df['5']:
    
    if (len(items)==1):
        theColumn.append('')
    
    elif(len(items)==2 and items=='––'):
        theColumn.append(items[0])
    elif(len(items)==2):
        theColumn.append('')
    
    elif(len(items)==3 and items!='100'):
        theColumn.append(items[0:2])
    elif(items=='100'):
        theColumn.append(items)
    
    elif(len(items)==4 and items!='100–'):
        theColumn.append(items[0:2])
    elif(items=='100–'):
        theColumn.append(items[0:3])
    
    elif(len(items)==5 and items=='99100'):
        theColumn.append(items[0:2])
    elif(len(items)==5 and items=='10099'):
        theColumn.append(items[0:3])
    
    else:
        theColumn.append(items[0:3])
print(len(theColumn))  
df['test 2 final']=theColumn
df

188

,Country Name,0,1,2,3,5,6,7,8,9,...,15,16,17,18,19,20,21,test,test 1,test 2 final
0,Afghanistan,63,89,53,3956,33,74,73,65,60,...,65,65,62,46,63,5,26,39,56,
1,Albania,91,93,90,9898,97,99,99,98,98,...,98,92,70x,54x,71x,–,–,98,98,
2,Algeria,93,95,89,8790,82,99,96,91,91,...,61,92,66,25,–,–,–,87,90,
3,Andorra,100,100,100,100100,100,–,99,98,98,...,92,–,–,–,–,–,–,100,100,100
4,Angola,41,63,23,3962,21,58,79,64,66,...,58,78,49,43,51,22,31,39,62,
5,Anguilla,98,98,–,9797,–,–,–,–,–,...,–,–,–,–,–,–,–,97,97,
6,Antigua and Barbuda,97,–,–,88–,–,–,99,99,86,...,0,–,–,–,–,–,–,88,–,
7,Argentina,100,100,100,9595,94,92,97,92,87,...,82,–,94,18,–,–,–,95,95,
8,Armenia,99,99,99,9296,83,99,97,94,96,...,94,–,57x,37,71,–,–,92,96,
9,Australia,100,100,100,100–,–,–,98,94,94,...,94,–,–,–,–,–,–,100,–,
10,Austria,100,100,100,100100,100,–,99,87,87,...,0,–,–,–,–,–,–,100,100,100
11,Azerbaijan,84,95,72,8992,87,98,98,97,98,...,97,–,36x,11,–,1x,–,89,92,
12,Bahamas,98,–,–,92–,–,–,95,94,94,...,94,100,–,–,–,–,–,92,–,
13,Bahrain,100,–,–,100–,–,–,99,99,99,...,99,98,–,–,–,–,–,100,–,
14,Bangladesh,97,98,97,4754,43,99,99,97,97,...,97,97,42,77,55,–,–,47,54,
15,Barbados,98,–,–,96–,–,–,99,97,97,...,96,–,–,–,–,–,–,96,–,
16,Belarus,98,98,99,9494,95,98,99,98,98,...,0,–,93,45,–,–,–,94,94,
17,Belgium,100,100,100,9999,99,–,99,98,98,...,94,–,–,–,–,–,–,99,99,
18,Belize,97,99,96,8791,84,94,98,95,96,...,0,91,67,55,71,–,–,87,91,
19,Benin,67,77,60,1425,5,96,86,82,78,...,75,85,23,25,44,73,77,14,25,
20,Bhutan,98,97,98,6372,57,99,99,98,97,...,0,89,74x,61x,–,–,–,63,72,
21,Bolivia (Plurinational State of),93,99,79,5364,27,99,99,99,99,...,97,87,62,22,–,–,–,53,64,
22,Bosnia and Herzegovina,98,97,98,9599,92,97,90,78,79,...,0,–,87,36,–,–,–,95,99,
23,Botswana,79,95,58,6075,39,98,98,95,96,...,95,92,14x,43x,75x,31,53,60,75,
24,Brazil,97,99,87,8691,58,99,89,86,98,...,94,93,50x,–,–,–,–,86,91,
25,British Virgin Islands,100,–,–,97–,–,–,–,–,–,...,–,–,–,–,–,–,–,97,–,
26,Brunei Darussalam,100,100,99,9696,97,99,99,99,99,...,0,95,–,–,–,–,–,96,96,
27,Bulgaria,99,99,99,8687,84,96,94,92,92,...,90,–,–,–,–,–,–,86,87,
28,Burkina Faso,54,79,43,2348,12,98,95,91,91,...,91,92,52,40,61,75,90,23,48,
29,Burundi,56,88,52,5046,51,93,97,94,94,...,94,85,63,36,69,40,46,50,46,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,Sierra Leone,58,75,47,1524,8,92,97,84,84,...,84,90,72,85,72,49,64,15,24,
159,Singapore,100,100,–,100100,–,99,98,97,96,...,78,–,–,–,–,–,–,100,100,
160,Slovakia,98,99,97,9999,98,0,99,96,96,...,96,–,–,–,–,–,–,99,99,
161,Slovenia,100,100,99,9999,99,–,98,94,94,...,50,–,–,–,–,–,–,99,99,
162,Solomon Islands,64,90,56,3176,18,98,99,99,99,...,87,85,79,37,61,70,86,31,76,
163,Somalia,40,70,20,1628,8,37,52,42,47,...,0,67,13x,13x,–,11x,12x,16,28,
164,South Africa,85,97,63,7376,69,74,78,66,66,...,69,80,88,51,68,–,–,73,76,
165,South Sudan,50,60,48,1028,6,37,35,26,31,...,0,75,48x,39x,57,46,66,10,28,
166,Spain,100,100,100,100100,100,–,99,97,97,...,0,–,–,–,–,–,–,100,100,100
167,Sri Lanka,92,96,91,9489,95,99,99,99,99,...,0,95,58x,51x,85x,3x,5x,94,89,
168,State of Palestine,88,86,94,9695,99,99,99,99,99,...,99,–,77,32,–,–,–,96,95,
169,Sudan,59,73,52,3558,23,96,97,93,93,...,93,77,48,20,–,30x,25x,35,58,
170,Suriname,95,98,88,7988,61,–,92,91,91,...,0,93,76x,42x,–,43x,61x,79,88,
171,Swaziland,68,95,60,5858,58,97,96,90,90,...,90,90,60,84,63,2x,10x,58,58,
172,Sweden,100,100,100,9999,100,26,99,98,98,...,97,–,–,–,–,–,–,99,99,100
173,Switzerland,100,100,100,100100,100,–,99,97,97,...,81,–,–,–,–,–,–,100,100,100
174,Syrian Arab Republic,97,99,94,9396,89,66,61,42,48,...,0,91,77x,50x,–,–,–,93,96,
175,Tajikistan,74,92,68,9594,96,98,98,96,97,...,0,–,63,60,57,1x,2x,95,94,
176,Thailand,98,99,97,9594,96,99,99,99,99,...,0,95,80,73,76,–,–,95,94,
177,The former Yugoslav Republic of Macedonia,97,96,98,9197,83,99,97,95,95,...,0,–,93x,62,–,–,–,91,97,
178,Timor-Leste,70,91,60,4473,30,85,95,85,83,...,0,81,71x,71x,73x,41x,41x,44,73,
179,Togo,63,90,45,1428,5,79,93,89,89,...,89,83,49,19,58,43,65,14,28,
180,Tokelau,100,–,100,93–,93,–,–,–,–,...,–,–,–,–,–,–,–,93,–,
181,Tonga,100,100,100,9397,92,80,83,78,80,...,0,–,–,–,64,–,–,93,97,
182,Trinidad and Tobago,97,–,–,92–,–,–,97,97,84,...,91,–,74x,–,–,–,–,92,–,
183,Tunisia,94,100,83,9398,83,95,99,98,98,...,0,96,60,65,–,–,–,93,98,
184,Turkey,99,99,100,9699,89,96,99,98,98,...,98,90,–,–,–,–,–,96,99,
185,Turkmenistan,94,91,98,9794,99,98,99,98,98,...,0,–,59,47,–,–,–,97,94,
186,Turks and Caicos Islands,94,–,–,88–,–,–,–,–,–,...,–,–,–,–,–,–,–,88,–,
187,Tuvalu,99,100,99,9192,91,98,99,94,94,...,0,–,–,44x,79x,–,–,91,92,

In [108]:
df['column 4 test']=df['test 1'] + df['test 2 final']
df.head()

,Country Name,0,1,2,3,5,6,7,8,9,...,16,17,18,19,20,21,test,test 1,test 2 final,column 4 test
0,Afghanistan,63,89,53,3956,33,74,73,65,60,...,65,62,46,63,5,26,39,56,,56
1,Albania,91,93,90,9898,97,99,99,98,98,...,92,70x,54x,71x,–,–,98,98,,98
2,Algeria,93,95,89,8790,82,99,96,91,91,...,92,66,25,–,–,–,87,90,,90
3,Andorra,100,100,100,100100,100,–,99,98,98,...,–,–,–,–,–,–,100,100,100,100100
4,Angola,41,63,23,3962,21,58,79,64,66,...,78,49,43,51,22,31,39,62,,62

In [109]:
df.drop('test 1', axis=1, inplace= True)
df.drop('test 2 final', axis=1, inplace= True)
df.head()

,Country Name,0,1,2,3,5,6,7,8,9,...,14,15,16,17,18,19,20,21,test,column 4 test
0,Afghanistan,63,89,53,3956,33,74,73,65,60,...,0,65,65,62,46,63,5,26,39,56
1,Albania,91,93,90,9898,97,99,99,98,98,...,0,98,92,70x,54x,71x,–,–,98,98
2,Algeria,93,95,89,8790,82,99,96,91,91,...,0,61,92,66,25,–,–,–,87,90
3,Andorra,100,100,100,100100,100,–,99,98,98,...,0,92,–,–,–,–,–,–,100,100100
4,Angola,41,63,23,3962,21,58,79,64,66,...,53,58,78,49,43,51,22,31,39,62

In [110]:
test=[]
for items in df['column 4 test']:
    if((len(items)==1) or (len(items)==2) or (len(items)==3) or (len(items)==4)):
        test.append(items)
    if (len(items)==5):
        test.append(items[0:2])
    if (len(items)==6):
        test.append(items[0:3]) 
print(len(test))
df.head()

188

,Country Name,0,1,2,3,5,6,7,8,9,...,14,15,16,17,18,19,20,21,test,column 4 test
0,Afghanistan,63,89,53,3956,33,74,73,65,60,...,0,65,65,62,46,63,5,26,39,56
1,Albania,91,93,90,9898,97,99,99,98,98,...,0,98,92,70x,54x,71x,–,–,98,98
2,Algeria,93,95,89,8790,82,99,96,91,91,...,0,61,92,66,25,–,–,–,87,90
3,Andorra,100,100,100,100100,100,–,99,98,98,...,0,92,–,–,–,–,–,–,100,100100
4,Angola,41,63,23,3962,21,58,79,64,66,...,53,58,78,49,43,51,22,31,39,62

In [111]:
df['Column 4 final']=test
df.drop('3', axis=1, inplace= True)
df.rename({'test':'3'}, axis=1, inplace=True)
df.rename({'Column 4 final':'4'}, axis=1, inplace=True)
df.head()

,Country Name,0,1,2,5,6,7,8,9,10,...,15,16,17,18,19,20,21,3,column 4 test,4
0,Afghanistan,63,89,53,33,74,73,65,60,62,...,65,65,62,46,63,5,26,39,56,56
1,Albania,91,93,90,97,99,99,98,98,96,...,98,92,70x,54x,71x,–,–,98,98,98
2,Algeria,93,95,89,82,99,96,91,91,94,...,61,92,66,25,–,–,–,87,90,90
3,Andorra,100,100,100,100,–,99,98,98,97,...,92,–,–,–,–,–,–,100,100100,100
4,Angola,41,63,23,21,58,79,64,66,49,...,58,78,49,43,51,22,31,39,62,62

In [112]:
df = df[['Country Name', '0', '1', '2', '3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21']]

In [113]:
df.head()

,Country Name,0,1,2,3,4,5,6,7,8,...,12,13,14,15,16,17,18,19,20,21
0,Afghanistan,63,89,53,39,56,33,74,73,65,...,65,65,0,65,65,62,46,63,5,26
1,Albania,91,93,90,98,98,97,99,99,98,...,98,98,0,98,92,70x,54x,71x,–,–
2,Algeria,93,95,89,87,90,82,99,96,91,...,91,91,0,61,92,66,25,–,–,–
3,Andorra,100,100,100,100,100,100,–,99,98,...,94,98,0,92,–,–,–,–,–,–
4,Angola,41,63,23,39,62,21,58,79,64,...,64,64,53,58,78,49,43,51,22,31

In [114]:
theColumn1=[]
for items in df['5']:
    
    if (len(items)==1):
        theColumn1.append(items)
    
    elif(len(items)==2 and items=='––'):
        theColumn1.append(items[0])
    elif(len(items)==2):
        theColumn1.append(items)
    
    elif(len(items)==3 and items!='100'):
        theColumn1.append(items[-1:])
    elif(items=='100'):
        theColumn1.append(items)
    
    elif(len(items)==4 and items!='100–'):
        theColumn1.append(items[-2:])
    elif(items=='100–'):
        theColumn1.append(items[-1:])
    
    elif(len(items)==5 and items=='99100'):
        theColumn1.append(items[-3:])
    elif(len(items)==5 and items=='10099'):
        theColumn1.append(items[-2:])
    
    else:
        theColumn1.append(items[-3:])
print(len(theColumn1))
df['final 5']= theColumn1
df.drop('5', axis=1, inplace= True)
df.rename({'final 5':'5'}, axis=1, inplace=True)
df.head()

188

,Country Name,0,1,2,3,4,6,7,8,9,...,13,14,15,16,17,18,19,20,21,5
0,Afghanistan,63,89,53,39,56,74,73,65,60,...,65,0,65,65,62,46,63,5,26,33
1,Albania,91,93,90,98,98,99,99,98,98,...,98,0,98,92,70x,54x,71x,–,–,97
2,Algeria,93,95,89,87,90,99,96,91,91,...,91,0,61,92,66,25,–,–,–,82
3,Andorra,100,100,100,100,100,–,99,98,98,...,98,0,92,–,–,–,–,–,–,100
4,Angola,41,63,23,39,62,58,79,64,66,...,64,53,58,78,49,43,51,22,31,21

In [115]:
df = df[['Country Name', '0', '1', '2', '3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21']]
df.head()

,Country Name,0,1,2,3,4,5,6,7,8,...,12,13,14,15,16,17,18,19,20,21
0,Afghanistan,63,89,53,39,56,33,74,73,65,...,65,65,0,65,65,62,46,63,5,26
1,Albania,91,93,90,98,98,97,99,99,98,...,98,98,0,98,92,70x,54x,71x,–,–
2,Algeria,93,95,89,87,90,82,99,96,91,...,91,91,0,61,92,66,25,–,–,–
3,Andorra,100,100,100,100,100,100,–,99,98,...,94,98,0,92,–,–,–,–,–,–
4,Angola,41,63,23,39,62,21,58,79,64,...,64,64,53,58,78,49,43,51,22,31

* Now that we have dealth with all the merged column and seperated them out.
* our next step is to remove all the 'x' from the columns that have them.
* to do this we shall look at again the different lengths of items in the columns and append it in a list.
* add that list back to the data frame.

In [116]:
col_17=[]
for items in df['17']:
    if ((len(items)==1)):
        col_17.append(items)
        
    elif(len(items)==2 and items[1]=='x'):
        col_17.append(items[0])
        
    elif (len(items)==2):
        col_17.append(items)
        
    elif(len(items)==3 and items[2]=='x'):
        col_17.append(items[0:2])
        
col_18=[]
for items in df['18']:
    if ((len(items)==1)):
        col_18.append(items)
        
    elif(len(items)==2 and items[1]=='x'):
        col_18.append(items[0])
        
    elif (len(items)==2):
        col_18.append(items)
        
    elif(len(items)==3 and items[2]=='x'):
        col_18.append(items[0:2])

col_19=[]
for items in df['19']:
    if ((len(items)==1)):
        col_19.append(items)
        
    elif(len(items)==2 and items[1]=='x'):
        col_19.append(items[0])
        
    elif (len(items)==2):
        col_19.append(items)
        
    elif(len(items)==3 and items[2]=='x'):
        col_19.append(items[0:2])

col_20=[]
for items in df['20']:
    if ((len(items)==1)):
        col_20.append(items)
        
    elif(len(items)==2 and items[1]=='x'):
        col_20.append(items[0])
        
    elif (len(items)==2):
        col_20.append(items)
        
    elif(len(items)==3 and items[2]=='x'):
        col_20.append(items[0:2])

col_21=[]
for items in df['21']:
    if ((len(items)==1)):
        col_21.append(items)
        
    elif(len(items)==2 and items[1]=='x'):
        col_21.append(items[0])
        
    elif (len(items)==2):
        col_21.append(items)
        
    elif(len(items)==3 and items[2]=='x'):
        col_21.append(items[0:2])


#dropping columns
toDrop=['17','18','19','20','21']
for items in toDrop:
    df.drop(items, axis=1, inplace= True)

#assigning the list to data frame.    
df['17'] = col_17
df['18'] = col_18
df['19'] = col_19
df['20'] = col_20
df['21'] = col_21

#replacing the - with empty string and setting the index to the country name.
df1 = df.replace(to_replace='–', value='')
df1.set_index(['Country Name'], inplace= True)
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,63,89,53,39,56,33,74,73,65,60,...,65,65,0,65,65,62,46,63,5,26
Albania,91,93,90,98,98,97,99,99,98,98,...,98,98,0,98,92,70,54,71,,
Algeria,93,95,89,87,90,82,99,96,91,91,...,91,91,0,61,92,66,25,,,
Andorra,100,100,100,100,100,100,,99,98,98,...,94,98,0,92,,,,,,
Angola,41,63,23,39,62,21,58,79,64,66,...,64,64,53,58,78,49,43,51,22,31

* we now begin working on the second part of the pdf, which is countries starting from uganda to zimbabwe.
* after wrangling all the data we shall join both data frames.

In [117]:
Country=[]
Col_1=[]
Col_2=[]
Col_3=[]
Col_4=[]
Col_5=[]
Col_6=[]
Col_7=[]
Col_8=[]
Col_9=[]
Col_10=[]
Col_11=[]
for table in tables:
    for row in table[5:]:
        if(row[0]=='SUMMARY'):
            break
        Country.append(row[0])
        Col_1.append(row[1])
        Col_2.append(row[2])
        Col_3.append(row[3])
        Col_4.append(row[4])
        Col_5.append(row[5])
        Col_6.append(row[6])
        Col_7.append(row[7])
        Col_8.append(row[8])
        Col_9.append(row[9])
        Col_10.append(row[10])
        Col_11.append(row[11])
        print (row[0:22])
    print ('==========================\n')

['Afghanistan', '63', '89', '53', '3956', '33', '74', '73', '65', '60', '62', '39', '65', '65', '0', '65', '65', '62', '46', '63', '5', '26']
['Albania', '91', '93', '90', '9898', '97', '99', '99', '98', '98', '96', '98', '98', '98', '0', '98', '92', '70x', '54x', '71x', '–', '–']
['Algeria', '93', '95', '89', '8790', '82', '99', '96', '91', '91', '94', '96', '91', '91', '0', '61', '92', '66', '25', '–', '–', '–']
['Andorra', '100', '100', '100', '100100', '100', '–', '99', '98', '98', '97', '90', '94', '98', '0', '92', '–', '–', '–', '–', '–', '–']
['Angola', '41', '63', '23', '3962', '21', '58', '79', '64', '66', '49', '26', '64', '64', '53', '58', '78', '49', '43', '51', '22', '31']
['Anguilla', '98', '98', '–', '9797', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–']
['Antigua and Barbuda', '97', '–', '–', '88–', '–', '–', '99', '99', '86', '98', '87', '99', '99', '0', '0', '–', '–', '–', '–', '–', '–']
['Argentina', '100', '100', '100', '9595', '94', '92', '97', '92', '87', '90', '88', '92', '92', '75', '82', '–', '94', '18', '–', '–', '–']
['Armenia', '99', '99', '99', '9296', '83', '99', '97', '94', '96', '97', '97', '94', '94', '94', '94', '–', '57x', '37', '71', '–', '–']
['Australia', '100', '100', '100', '100–', '–', '–', '98', '94', '94', '95', '94', '94', '94', '87', '94', '–', '–', '–', '–', '–', '–']
['Austria', '100', '100', '100', '100100', '100', '–', '99', '87', '87', '95', '89', '87', '87', '61', '0', '–', '–', '–', '–', '–', '–']
['Azerbaijan', '84', '95', '72', '8992', '87', '98', '98', '97', '98', '98', '98', '97', '97', '0', '97', '–', '36x', '11', '–', '1x', '–']
['Bahamas', '98', '–', '–', '92–', '–', '–', '95', '94', '94', '89', '74', '94', '94', '0', '94', '100', '–', '–', '–', '–', '–']
['Bahrain', '100', '–', '–', '100–', '–', '–', '99', '99', '99', '99', '99', '99', '99', '98', '99', '98', '–', '–', '–', '–', '–']
['Bangladesh', '97', '98', '97', '4754', '43', '99', '99', '97', '97', '94', '93', '97', '97', '0', '97', '97', '42', '77', '55', '–', '–']
['Barbados', '98', '–', '–', '96–', '–', '–', '99', '97', '97', '92', '87', '97', '97', '0', '96', '–', '–', '–', '–', '–', '–']
['Belarus', '98', '98', '99', '9494', '95', '98', '99', '98', '98', '98', '98', '96', '11', '0', '0', '–', '93', '45', '–', '–', '–']
['Belgium', '100', '100', '100', '9999', '99', '–', '99', '98', '98', '96', '85', '97', '97', '87', '94', '–', '–', '–', '–', '–', '–']
['Belize', '97', '99', '96', '8791', '84', '94', '98', '95', '96', '95', '96', '95', '95', '0', '0', '91', '67', '55', '71', '–', '–']
['Benin', '67', '77', '60', '1425', '5', '96', '86', '82', '78', '74', '0', '82', '82', '0', '75', '85', '23', '25', '44', '73', '77']
['Bhutan', '98', '97', '98', '6372', '57', '99', '99', '98', '97', '97', '90', '98', '98', '0', '0', '89', '74x', '61x', '–', '–', '–']
['Bolivia (Plurinational State of)', '93', '99', '79', '5364', '27', '99', '99', '99', '99', '99', '0', '99', '99', '99', '97', '87', '62', '22', '–', '–', '–']
['Bosnia and Herzegovina', '98', '97', '98', '9599', '92', '97', '90', '78', '79', '83', '78', '78', '69', '0', '0', '–', '87', '36', '–', '–', '–']
['Botswana', '79', '95', '58', '6075', '39', '98', '98', '95', '96', '97', '74', '95', '95', '95', '95', '92', '14x', '43x', '75x', '31', '53']
['Brazil', '97', '99', '87', '8691', '58', '99', '89', '86', '98', '96', '72', '86', '86', '94', '94', '93', '50x', '–', '–', '–', '–']
['British Virgin Islands', '100', '–', '–', '97–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–']
['Brunei Darussalam', '100', '100', '99', '9696', '97', '99', '99', '99', '99', '98', '97', '99', '99', '0', '0', '95', '–', '–', '–', '–', '–']
['Bulgaria', '99', '99', '99', '8687', '84', '96', '94', '92', '92', '92', '88', '91', '92', '0', '90', '–', '–', '–', '–', '–', '–']
['Burkina Faso', '54', '79', '43', '2348', '12', '98', '95', '91', '91', '88', '50', '91', '91', '91', '91', '92', '52', '40', '61', '75', '90']
['Burundi', '56', '88', '52', '5046', '51', '93', '97', '94', '94', '93', '72', '94', '94', '96', '94', '85', '63', '36', '69', '40', '46']
['Cabo Verde', '86', '93', '74', '6573', '51', '96', '96', '96', '95', '92', '95', '96', '96', '0', '0', '92', '–', '–', '–', '–', '–']
['Cambodia', '75', '96', '70', '4988', '39', '97', '92', '90', '87', '81', '58', '90', '90', '0', '87', '93', '69', '35', '61', '4x', '5x']
['Cameroon', '65', '84', '43', '3956', '19', '70', '92', '85', '83', '78', '0', '85', '85', '80', '84', '85', '28', '16', '33', '55', '71']
['Canada', '99', '–', '–', '99–', '–', '–', '96', '91', '91', '90', '86', '55', '91', '0', '79', '–', '–', '–', '–', '–', '–']
['Central African Republic', '54', '74', '41', '2549', '9', '74', '69', '47', '47', '49', '0', '47', '47', '0', '47', '60', '30x', '16x', '–', '36x', '47x']
['Chad', '43', '78', '32', '1033', '3', '56', '60', '46', '44', '58', '0', '46', '46', '0', '0', '80', '26', '20', '23', '36', '77']
['Chile', '100', '100', '100', '100100', '99', '97', '99', '95', '95', '93', '87', '95', '95', '0', '90', '–', '–', '–', '–', '–', '–']
['China', '96', '96', '96', '7586', '61', '99', '99', '99', '99', '99', '99', '99', '0', '0', '0', '–', '–', '–', '–', '–', '–']
['Colombia', '97', '100', '86', '8488', '72', '88', '93', '91', '91', '93', '87', '91', '91', '90', '89', '90', '64x', '54x', '54x', '–', '3x']
['Comoros', '84', '93', '80', '3447', '29', '94', '96', '91', '92', '99', '0', '91', '91', '0', '0', '85', '38', '38', '45', '41', '59']
['Congo', '68', '85', '37', '1520', '6', '85', '85', '80', '80', '80', '0', '80', '80', '80', '80', '85', '28', '28', '51', '61', '66']
['Cook Islands', '100', '–', '–', '98–', '–', '99', '99', '99', '99', '90', '90', '99', '99', '0', '0', '–', '–', '–', '–', '–', '–']
['Costa Rica', '100', '100', '100', '9798', '94', '89', '99', '97', '97', '93', '87', '97', '97', '0', '94', '–', '77', '40', '–', '–', '–']
["Côte d'Ivoire", '73', '89', '54', '3045', '13', '95', '98', '85', '80', '77', '0', '85', '85', '0', '83', '90', '38', '17', '43', '37', '67']
['Croatia', '100', '100', '100', '9798', '96', '99', '98', '93', '93', '90', '96', '93', '93', '0', '0', '–', '–', '–', '–', '–', '–']
['Cuba', '95', '97', '90', '9192', '88', '99', '99', '99', '98', '99', '99', '99', '99', '0', '0', '–', '93', '61', '93', '–', '–']
['Cyprus', '100', '100', '100', '99100', '99', '–', '98', '97', '97', '90', '88', '97', '96', '0', '81', '–', '–', '–', '–', '–', '–']
['Czechia', '100', '100', '100', '9999', '99', '–', '98', '96', '96', '98', '93', '96', '96', '0', '0', '–', '–', '–', '–', '–', '–']
["Democratic People's Republic of Korea", '100', '100', '99', '7783', '68', '97', '97', '96', '99', '99', '98', '96', '96', '0', '0', '97', '80x', '74x', '–', '–', '–']
['Democratic Republic of the Congo', '42', '70', '21', '2023', '18', '80', '80', '79', '74', '77', '0', '79', '79', '0', '77', '85', '42', '39', '55', '56', '70']
['Denmark', '100', '100', '100', '100100', '100', '–', '97', '94', '94', '94', '85', '0', '94', '0', '94', '–', '–', '–', '–', '–', '–']
['Djibouti', '77', '83', '55', '5163', '13', '90', '90', '84', '84', '75', '82', '84', '84', '86', '82', '85', '94', '94', '–', '20x', '32']
['Dominica', '97', '–', '–', '78–', '–', '98', '99', '99', '99', '96', '92', '99', '99', '0', '0', '–', '–', '–', '–', '–', '–']
['Dominican Republic', '94', '97', '86', '8385', '74', '99', '98', '87', '82', '85', '0', '80', '73', '75', '30', '90', '73', '48', '65', '–', '–']
['Ecuador', '93', '100', '80', '8689', '80', '84', '94', '83', '79', '86', '76', '84', '84', '80', '84', '88', '–', '46', '–', '–', '–']
['Egypt', '98', '99', '98', '9397', '90', '96', '96', '95', '95', '95', '96', '95', '95', '0', '0', '80', '68', '28', '68', '–', '–']
['El Salvador', '93', '98', '83', '9193', '87', '99', '97', '93', '95', '90', '87', '93', '93', '93', '90', '90', '80', '70', '–', '–', '–']
['Equatorial Guinea', '50', '78', '31', '7580', '71', '48', '40', '19', '20', '30', '0', '19', '19', '0', '0', '70', '54', '40', '62', '23', '38']
['Eritrea', '19', '66', '6', '1129', '6', '97', '97', '95', '95', '93', '85', '95', '95', '96', '95', '94', '45x', '43x', '–', '20x', '71x']
['Estonia', '100', '100', '99', '100100', '100', '95', '94', '93', '93', '93', '92', '93', '93', '85', '0', '–', '–', '–', '–', '–', '–']
['Ethiopia', '39', '77', '30', '718', '4', '75', '86', '77', '75', '70', '0', '77', '77', '63', '76', '80', '30', '30', '35', '45', '64']
['Fiji', '94', '98', '89', '9696', '95', '99', '99', '99', '99', '94', '94', '99', '99', '99', '99', '94', '–', '–', '–', '–', '–']
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
==========================

['Finland', '100', '100', '100', '99', '9999', '–', '99', '92', '92', '94', '85', '0', '92', '84', '87', '–', '–', '–', '–', '–', '–']
['France', '100', '100', '100', '99', '9999', '–', '99', '97', '97', '90', '79', '88', '96', '0', '91', '–', '–', '–', '–', '–', '–']
['Gabon', '88', '92', '59', '41', '4232', '94', '83', '75', '74', '64', '0', '75', '75', '0', '0', '90', '68', '26', '67', '39', '36']
['Gambia', '80', '88', '68', '42', '4635', '98', '99', '95', '95', '97', '79', '95', '95', '95', '95', '92', '68', '59', '65', '47', '69']
['Georgia', '93', '98', '87', '85', '9573', '98', '97', '92', '92', '93', '85', '92', '92', '75', '75', '–', '74x', '40x', '–', '–', '–']
['Germany', '100', '100', '100', '99', '9999', '–', '95', '95', '94', '97', '93', '88', '93', '66', '86', '–', '–', '–', '–', '–', '–']
['Ghana', '78', '88', '66', '14', '199', '94', '94', '93', '95', '89', '75', '93', '93', '94', '93', '88', '56', '49', '77', '47', '68']
['Greece', '100', '100', '100', '99', '9998', '–', '99', '99', '99', '97', '83', '96', '99', '20', '96', '–', '–', '–', '–', '–', '–']
['Grenada', '96', '–', '–', '78', '––', '–', '98', '96', '98', '95', '85', '96', '96', '0', '0', '–', '–', '–', '–', '–', '–']
['Guatemala', '94', '97', '89', '67', '8153', '87', '96', '80', '82', '86', '65', '80', '80', '82', '81', '90', '52', '49', '50', '–', '–']
['Guinea', '67', '88', '55', '22', '3415', '72', '65', '57', '42', '54', '0', '57', '57', '0', '0', '80', '37', '34', '37', '26', '47']
['Guinea-Bissau', '69', '85', '54', '21', '358', '94', '95', '87', '87', '81', '0', '87', '87', '61', '80', '80', '34', '35', '51', '81', '90']
['Guyana', '95', '100', '93', '86', '8985', '95', '97', '97', '94', '99', '94', '97', '97', '96', '92', '99', '84', '43', '71', '7', '5']
['Haiti', '64', '81', '40', '31', '3722', '72', '78', '58', '56', '53', '26', '58', '58', '48', '0', '88', '38', '53', '40', '12', '19']
['Holy See', '–', '–', '–', '–', '––', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–']
['Honduras', '92', '99', '84', '80', '8475', '99', '99', '97', '97', '88', '0', '97', '97', '97', '97', '94', '64', '60', '62', '–', '–']
['Hungary', '100', '100', '100', '98', '9899', '99', '99', '99', '99', '99', '99', '0', '99', '0', '98', '–', '–', '–', '–', '–', '–']
['Iceland', '100', '100', '100', '99', '99100', '–', '96', '91', '91', '91', '95', '0', '91', '0', '90', '–', '–', '–', '–', '–', '–']
['India', '88', '93', '85', '44', '6534', '89', '91', '88', '86', '88', '76', '88', '80', '4', '0', '87', '73', '51', '71x', '–', '–']
['Indonesia', '90', '97', '81', '68', '7757', '81', '95', '79', '80', '76', '56', '79', '79', '0', '0', '85', '75', '39', '74', '3x', '3x']
['Iran (Islamic Republic of)', '95', '97', '89', '88', '9279', '99', '99', '99', '99', '99', '98', '99', '99', '0', '0', '95', '76x', '61x', '–', '–', '–']
['Iraq', '86', '90', '78', '86', '8686', '94', '73', '63', '68', '66', '64', '61', '63', '34', '0', '75', '74', '23', '–', '–', '–']
['Ireland', '99', '99', '99', '92', '9195', '18', '98', '95', '95', '92', '0', '95', '95', '0', '91', '–', '–', '–', '–', '–', '–']
['Israel', '100', '100', '100', '100', '100100', '–', '94', '94', '94', '97', '97', '95', '94', '81', '93', '–', '–', '–', '–', '–', '–']
['Italy', '100', '100', '100', '99', '9999', '–', '97', '93', '93', '85', '83', '93', '93', '0', '89', '–', '–', '–', '–', '–', '–']
['Jamaica', '93', '97', '88', '85', '8487', '96', '99', '99', '99', '95', '85', '98', '99', '0', '0', '80', '82', '64', '–', '–', '–']
['Japan', '99', '–', '–', '100', '––', '84', '99', '99', '99', '96', '93', '0', '99', '0', '99', '–', '–', '–', '–', '–', '–']
['Jordan', '99', '99', '97', '97', '9796', '99', '99', '98', '98', '96', '99', '98', '98', '97', '0', '90', '77', '20', '69', '–', '–']
['Kazakhstan', '91', '97', '84', '98', '9799', '95', '93', '82', '82', '99', '99', '82', '82', '0', '97', '–', '81', '62', '–', '–', '–']
['Kenya', '58', '83', '50', '30', '3528', '99', '96', '89', '88', '75', '32', '89', '89', '74', '78', '85', '66', '54', '72', '56', '59']
['Kiribati', '64', '90', '44', '40', '4932', '79', '82', '81', '82', '80', '79', '81', '81', '79', '79', '90', '81x', '62x', '27x', '–', '–']
['Kuwait', '100', '–', '–', '100', '––', '99', '99', '99', '99', '93', '96', '99', '99', '0', '99', '95', '–', '–', '–', '–', '–']
['Kyrgyzstan', '87', '97', '82', '97', '9399', '97', '97', '96', '97', '97', '98', '96', '96', '0', '0', '–', '60', '33', '56', '–', '–']
["Lao People's Democratic Republic", '80', '92', '73', '73', '9360', '78', '85', '82', '83', '76', '0', '82', '82', '0', '78', '90', '54', '42', '–', '43', '50']
['Latvia', '99', '99', '98', '93', '9784', '96', '99', '98', '98', '93', '89', '98', '98', '83', '82', '–', '–', '–', '–', '–', '–']
['Lebanon', '92', '–', '–', '95', '––', '–', '84', '81', '75', '79', '75', '81', '81', '0', '0', '–', '74x', '44x', '–', '–', '–']
['Lesotho', '72', '87', '66', '44', '4643', '98', '98', '93', '90', '90', '82', '93', '93', '0', '93', '85', '63', '53', '61', '–', '–']
['Liberia', '70', '80', '60', '17', '286', '97', '99', '79', '79', '80', '0', '79', '79', '48', '79', '89', '51', '60', '78', '44', '62']
['Libya', '97', '–', '–', '100', '––', '99', '98', '97', '97', '97', '96', '97', '97', '97', '96', '–', '–', '–', '–', '–', '–']
['Liechtenstein', '100', '–', '–', '100', '––', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–']
['Lithuania', '97', '100', '93', '94', '9786', '98', '97', '94', '94', '94', '92', '95', '94', '0', '82', '–', '–', '–', '–', '–', '–']
['Luxembourg', '100', '100', '100', '98', '9799', '–', '99', '99', '99', '99', '86', '94', '99', '89', '95', '–', '–', '–', '–', '–', '–']
['Madagascar', '51', '82', '34', '10', '166', '70', '84', '77', '75', '58', '0', '77', '77', '78', '76', '78', '41', '15', '46', '73', '80']
['Malawi', '67', '87', '63', '44', '4943', '86', '89', '84', '83', '81', '61', '84', '84', '81', '83', '89', '78', '65', '67', '43', '57']
['Malaysia', '96', '99', '89', '100', '10099', '98', '99', '98', '98', '96', '99', '98', '98', '0', '0', '90', '–', '–', '–', '–', '–']
['Maldives', '98', '96', '100', '96', '9398', '99', '99', '99', '99', '99', '99', '99', '99', '0', '0', '99', '22x', '57x', '84x', '–', '–']
['Mali', '74', '91', '63', '31', '4622', '92', '86', '68', '67', '75', '0', '68', '68', '60', '70', '85', '23', '22x', '49', '79', '93']
['Malta', '100', '100', '100', '100', '100100', '–', '97', '97', '97', '93', '86', '97', '97', '0', '0', '–', '–', '–', '–', '–', '–']
['Marshall Islands', '78', '70', '99', '87', '9566', '94', '87', '71', '69', '75', '49', '73', '58', '38', '51', '–', '–', '38x', '63x', '–', '–']
['Mauritania', '70', '86', '45', '45', '6317', '85', '87', '73', '67', '70', '0', '73', '73', '73', '73', '80', '34', '19', '35', '18', '67']
['Mauritius', '100', '100', '100', '93', '9493', '98', '97', '96', '96', '92', '92', '72', '96', '92', '10', '95', '–', '–', '–', '–', '–']
['Mexico', '98', '100', '94', '89', '9181', '99', '99', '97', '96', '96', '98', '93', '97', '72', '92', '90', '73', '61', '–', '–', '–']
['Micronesia (Federated States of)', '88', '97', '86', '–', '––', '85', '95', '69', '68', '70', '74', '76', '61', '46', '63', '–', '–', '–', '–', '–', '–']
['Monaco', '100', '100', '–', '100', '100–', '89', '99', '99', '99', '99', '0', '99', '99', '0', '0', '–', '–', '–', '–', '–', '–']
['Mongolia', '83', '94', '56', '59', '6641', '99', '99', '99', '99', '98', '90', '99', '99', '0', '0', '–', '70', '42', '–', '–', '–']
['Montenegro', '98', '97', '99', '96', '9892', '88', '97', '89', '89', '47', '86', '75', '89', '0', '0', '–', '89x', '16x', '74', '–', '–']
['Montserrat', '97', '–', '–', '89', '––', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–', '–']
['Morocco', '83', '96', '64', '83', '8975', '99', '99', '99', '99', '99', '99', '99', '99', '99', '98', '90', '70', '22', '–', '–', '–']
['Mozambique', '47', '79', '32', '24', '4712', '95', '90', '80', '80', '91', '51', '80', '80', '76', '80', '83', '50', '55', '56', '36', '51']
['Myanmar', '68', '82', '60', '65', '7659', '88', '94', '90', '89', '91', '86', '90', '90', '0', '14', '87', '58', '62', '65', '19', '27']
['Namibia', '79', '97', '63', '34', '5515', '94', '98', '92', '92', '85', '0', '92', '92', '86', '81', '88', '68', '72', '63', '6', '24']
['Nauru', '100', '100', '–', '66', '66–', '99', '98', '91', '91', '98', '96', '91', '91', '0', '0', '–', '69x', '23x', '51x', '–', '–']
['Nepal', '88', '89', '87', '46', '5245', '93', '92', '87', '85', '83', '25', '87', '87', '0', '46', '82', '85', '37', '46', '–', '–']
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
==========================

['Netherlands', '100', '100', '100', '9898', '100', '–', '98', '95', '95', '94', '91', '93', '95', '0', '94', '–', '–', '–', '–', '–', '–']
['New Zealand', '100', '100', '100', '100100', '100', '–', '92', '92', '92', '92', '89', '92', '92', '66', '93', '–', '–', '–', '–', '–', '–']
['Nicaragua', '82', '97', '61', '7686', '63', '98', '99', '98', '99', '99', '0', '98', '98', '98', '98', '85', '58x', '65', '–', '–', '–']
['Niger', '46', '89', '36', '1344', '6', '77', '87', '67', '67', '74', '37', '67', '67', '61', '64', '85', '59', '41', '51', '20', '61']
['Nigeria', '67', '82', '54', '3339', '27', '64', '64', '49', '49', '51', '0', '49', '49', '0', '26', '63', '35', '34', '66', '44', '69']
['Niue', '98', '–', '–', '97–', '–', '99', '99', '99', '99', '99', '99', '99', '99', '0', '99', '–', '–', '–', '–', '–', '–']
['Norway', '100', '100', '100', '9898', '98', '–', '99', '96', '96', '96', '91', '0', '96', '0', '94', '–', '–', '–', '–', '–', '–']
['Oman', '91', '95', '78', '9999', '99', '99', '99', '99', '99', '99', '99', '99', '99', '0', '99', '98', '56', '59', '–', '–', '–']
['Pakistan', '89', '92', '87', '5874', '48', '85', '79', '72', '72', '61', '53', '72', '72', '0', '72', '80', '64', '38', '65', '0x', '1']
['Palau', '100', '100', '97', '100100', '100', '–', '99', '98', '98', '96', '95', '98', '98', '98', '98', '–', '–', '–', '–', '–', '–']
['Panama', '95', '99', '87', '7786', '59', '99', '96', '73', '72', '90', '92', '73', '73', '92', '83', '–', '82', '52', '–', '–', '–']
['Papua New Guinea', '37', '84', '29', '1955', '13', '89', '87', '72', '73', '70', '0', '66', '72', '0', '20', '75', '63x', '–', '–', '–', '–']
['Paraguay', '99', '99', '98', '9198', '81', '99', '99', '93', '89', '99', '92', '93', '93', '92', '99', '85', '–', '–', '–', '–', '–']
['Peru', '90', '95', '72', '7782', '58', '90', '94', '89', '88', '88', '66', '89', '89', '87', '86', '85', '62', '32', '61', '–', '–']
['Philippines', '91', '96', '86', '7579', '72', '76', '87', '86', '72', '80', '66', '86', '86', '0', '36', '90', '64', '49', '50', '–', '–']
['Poland', '98', '99', '96', '9898', '98', '94', '99', '98', '92', '96', '94', '96', '98', '0', '0', '–', '–', '–', '–', '–', '–']
['Portugal', '100', '100', '100', '9999', '100', '32', '99', '98', '98', '98', '95', '98', '98', '0', '0', '–', '–', '–', '–', '–', '–']

In [118]:
df2=pd.DataFrame({'Country Name':Country,'0':Col_1,'1':Col_2,'2':Col_3,'3':Col_4,'4':Col_5,'5':Col_6,'6':Col_7,'7':Col_8,'8':Col_9,'9':Col_10,'10':Col_11})

df2 = df2[['Country Name', '0', '1', '2', '3','4','5','6','7','8','9','10']]

theRange=range(0,194)
df2.drop(df2.index[[theRange]], inplace = True)
df2.reset_index(drop= True, inplace= True)
df2

,Country Name,0,1,2,3,4,5,6,7,8,9,10
0,Uganda397332,192817938978,82,82,0,78,78,07887,80,4781,62,78
1,Ukraine9897100,969793754219,56,42,31,26,47,00–,92,59–,–,–
2,United Arab Emirates100100100,100100100999999,99,99,99,99,99,9299–,–,––,–,–
3,United Kingdom100100100,999999–9894,94,92,89,0,94,9092–,–,––,–,–
4,United Republic of Tanzania507937,243717999997,93,90,71,97,97,969690,55,4550,54,66
5,United States9910097,100100100–9795,94,92,0,93,93,7393–,–,––,–,–
6,Uruguay9910094,969695989795,95,95,92,95,95,094–,91,––,–,–
7,Uzbekistan–99–,100100100999999,99,99,99,99,99,9999–,68x,28x–,–,–
8,Vanuatu919987,536151737564,65,53,0,64,64,0078,72,4857,51,83
9,Venezuela (Bolivarian Republic of)979986,959872999884,82,88,53,84,84,47775,72x,38x–,–,–
10,Viet Nam919291,789172959696,95,99,95,96,96,0094,81,51–,9,10
11,Yemen708563,609044737671,65,70,49,71,71,597170,34,2533,–,–
12,Zambia618644,314919999991,87,93,58,91,91,909085,70,6475,41,68
13,Zimbabwe679454,395431959490,90,95,63,90,90,919080,51,4150,9,48

* we can see above that the countries have values merged into it.
* so our first step is to seperate them out. 
* we will be using regular expressions to do this.
* as we can see there are other columns that have merged values too
* we shall use similar techniques like we did earlier to seperate the merged values.

In [119]:
import re
number=[]

for items in df2['Country Name']:

    number.append(re.findall(r"[–0-9]+", items))
    
numbers=[]
for sublist in number:
    for item in sublist:
        numbers.append(item)
df2['test']=numbers


country=[]
countries=[]

for items in df2['Country Name']:

    country.append(re.findall(r"[A-z()\s]+", items))
for sublist in country:
    for items in sublist:
        countries.append(items)
df2['test 1']=countries

df2.drop('Country Name', axis=1, inplace= True)

In [120]:
list_0=[]
list_1=[]
list_2=[]

for items in df2['test']:
    if(items=='–99–'):
        
        list_0.append(items[0])
        list_1.append(items[1:3])
        list_2.append(items[3])
    elif(len(items)==6):
        list_0.append(items[0:2])
        list_1.append(items[2:4])
        list_2.append(items[4:6])
    elif(len(items)==7 and items!='9897100'):
        list_0.append(items[0:2])
        list_1.append(items[2:5])
        list_2.append(items[5:7])
    elif(items=='9897100'):
        list_0.append(items[0:2])
        list_1.append(items[2:4])
        list_2.append(items[4:7])
    else:
        list_0.append(items[0:3])
        list_1.append(items[3:6])
        list_2.append(items[6:9])
        
df2['List 0']=list_0
df2['List 1']=list_1
df2['List 2']=list_2
df2.drop('test', axis=1, inplace= True)
df2.head()

,0,1,2,3,4,5,6,7,8,9,10,test 1,List 0,List 1,List 2
0,192817938978,82,82,0,78,78,07887,80,4781,62,78,Uganda,39,73,32
1,969793754219,56,42,31,26,47,00–,92,59–,–,–,Ukraine,98,97,100
2,100100100999999,99,99,99,99,99,9299–,–,––,–,–,United Arab Emirates,100,100,100
3,999999–9894,94,92,89,0,94,9092–,–,––,–,–,United Kingdom,100,100,100
4,243717999997,93,90,71,97,97,969690,55,4550,54,66,United Republic of Tanzania,50,79,37

In [121]:
df2.rename(columns={'test 1' : 'Country Name'},inplace=True)
df2.rename(columns={'1' : 'List 9','2' : 'List 10','3' : 'List 11','4' : 'List 12','5' : 'List 13'},inplace=True)

list_3=[]
list_4=[]
list_5=[]
list_6=[]
list_7=[]
list_8=[]

for items in df2['0']:
    if(items=='999999–9894'):
        
        list_3.append(items[0:2])
        list_4.append(items[2:4])
        list_5.append(items[4:6])
        list_6.append(items[6])
        list_7.append(items[7:9])
        list_8.append(items[9:11])
        
    elif(len(items)==12):
        list_3.append(items[0:2])
        list_4.append(items[2:4])
        list_5.append(items[4:6])
        list_6.append(items[6:8])
        list_7.append(items[8:10])
        list_8.append(items[10:12])
    elif(items=='100100100–9795'):
        list_3.append(items[0:3])
        list_4.append(items[3:6])
        list_5.append(items[6:9])
        list_6.append(items[9])
        list_7.append(items[10:12])
        list_8.append(items[12:14])
    
    else:
        list_3.append(items[0:3])
        list_4.append(items[3:6])
        list_5.append(items[6:9])
        list_6.append(items[9:11])
        list_7.append(items[11:13])
        list_8.append(items[13:15])
        
df2['List 3']=list_3
df2['List 4']=list_4
df2['List 5']=list_5
df2['List 6']=list_6
df2['List 7']=list_7
df2['List 8']=list_8


df2.drop('0', axis=1, inplace= True)
df2.rename(columns={'9' : 'List 20','10':'List 21'},inplace=True)

list_14=[]
list_15=[]
list_16=[]

for items in df2['6']:
    if(len(items)==3):
        
        list_14.append(items[0])
        list_15.append(items[1])
        list_16.append(items[2])
    
    elif(len(items)==4 and items!='094–'):
        list_14.append(items[0])
        list_15.append(items[1])
        list_16.append(items[2:4])
    elif(items=='094–'):
        list_14.append(items[0])
        list_15.append(items[1:3])
        list_16.append(items[3])
        
    elif(len(items)==5 and items!='07887'):
        list_14.append(items[0:2])
        list_15.append(items[2:4])
        list_16.append(items[4])
    elif(items=='07887'):
        list_14.append(items[0])
        list_15.append(items[1:3])
        list_16.append(items[3:5])
    else:
        list_14.append(items[0:2])
        list_15.append(items[2:4])
        list_16.append(items[4:6])
df2['List 14']=list_14
df2['List 15']=list_15
df2['List 16']=list_16

df2.drop('6', axis=1, inplace= True)
df2

,List 9,List 10,List 11,List 12,List 13,7,8,List 20,List 21,Country Name,...,List 2,List 3,List 4,List 5,List 6,List 7,List 8,List 14,List 15,List 16
0,82,82,0,78,78,80,4781,62,78,Uganda,...,32,19,28,17,93,89,78,0,78,87
1,56,42,31,26,47,92,59–,–,–,Ukraine,...,100,96,97,93,75,42,19,0,0,–
2,99,99,99,99,99,–,––,–,–,United Arab Emirates,...,100,100,100,100,99,99,99,92,99,–
3,94,92,89,0,94,–,––,–,–,United Kingdom,...,100,99,99,99,–,98,94,90,92,–
4,93,90,71,97,97,55,4550,54,66,United Republic of Tanzania,...,37,24,37,17,99,99,97,96,96,90
5,94,92,0,93,93,–,––,–,–,United States,...,97,100,100,100,–,97,95,73,93,–
6,95,95,92,95,95,91,––,–,–,Uruguay,...,94,96,96,95,98,97,95,0,94,–
7,99,99,99,99,99,68x,28x–,–,–,Uzbekistan,...,–,100,100,100,99,99,99,99,99,–
8,65,53,0,64,64,72,4857,51,83,Vanuatu,...,87,53,61,51,73,75,64,0,0,78
9,82,88,53,84,84,72x,38x–,–,–,Venezuela (Bolivarian Republic of),...,86,95,98,72,99,98,84,47,77,5
10,95,99,95,96,96,81,51–,9,10,Viet Nam,...,91,78,91,72,95,96,96,0,0,94
11,65,70,49,71,71,34,2533,–,–,Yemen,...,63,60,90,44,73,76,71,59,71,70
12,87,93,58,91,91,70,6475,41,68,Zambia,...,44,31,49,19,99,99,91,90,90,85
13,90,95,63,90,90,51,4150,9,48,Zimbabwe,...,54,39,54,31,95,94,90,91,90,80

In [122]:
df2.rename(columns={'7' : 'List 17'},inplace=True)
df2 = df2[['Country Name', 'List 0', 'List 1', 'List 2', 'List 3','List 4','List 5','List 6','List 7','List 8','List 9','List 10','List 11','List 12','List 13','List 14','List 15','List 16','List 17','8','List 20','List 21']]

In [123]:
df2.head()

,Country Name,List 0,List 1,List 2,List 3,List 4,List 5,List 6,List 7,List 8,...,List 11,List 12,List 13,List 14,List 15,List 16,List 17,8,List 20,List 21
0,Uganda,39,73,32,19,28,17,93,89,78,...,0,78,78,0,78,87,80,4781,62,78
1,Ukraine,98,97,100,96,97,93,75,42,19,...,31,26,47,0,0,–,92,59–,–,–
2,United Arab Emirates,100,100,100,100,100,100,99,99,99,...,99,99,99,92,99,–,–,––,–,–
3,United Kingdom,100,100,100,99,99,99,–,98,94,...,89,0,94,90,92,–,–,––,–,–
4,United Republic of Tanzania,50,79,37,24,37,17,99,99,97,...,71,97,97,96,96,90,55,4550,54,66

In [124]:
list_18=[]
list_19=[]


for items in df2['8']:
    if(len(items)==2):
        
        list_18.append(items[0])
        list_19.append(items[1])
 
    elif(len(items)==3):
        list_18.append(items[0:2])
        list_19.append(items[2])
    else:
        list_18.append(items[0:2])
        list_19.append(items[2:4])

In [125]:
df2['List 18']= list_18
df2['List 19']= list_19   

df2.drop('8', axis=1, inplace= True)

df2 = df2.replace(to_replace='x', value='')
df2.head()


new_list17=[]
for items in df2['List 17']:
    new_list17.append(re.findall(r"[^x]+", items))
    
the_list17=[]    
for sublist in new_list17:
    for items in sublist:
        the_list17.append(items)
#print(the_list17)       


new_list19=[]
for items in df2['List 19']:
    new_list19.append(re.findall(r"[^x]+", items))
    
the_list19=[]    
for sublist in new_list19:
    for items in sublist:
        the_list19.append(items)
#print(the_list19) 

toDrop = ['List 17','List 19']

for items in toDrop:
    df2.drop(items, axis=1, inplace= True)

df2['17']=the_list17
df2['19']=the_list19
df2.head()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,Country Name,List 0,List 1,List 2,List 3,List 4,List 5,List 6,List 7,List 8,...,List 12,List 13,List 14,List 15,List 16,List 20,List 21,List 18,17,19
0,Uganda,39,73,32,19,28,17,93,89,78,...,78,78,0,78,87,62,78,47,80,81
1,Ukraine,98,97,100,96,97,93,75,42,19,...,26,47,0,0,–,–,–,59,92,–
2,United Arab Emirates,100,100,100,100,100,100,99,99,99,...,99,99,92,99,–,–,–,–,–,–
3,United Kingdom,100,100,100,99,99,99,–,98,94,...,0,94,90,92,–,–,–,–,–,–
4,United Republic of Tanzania,50,79,37,24,37,17,99,99,97,...,97,97,96,96,90,54,66,45,55,50

In [126]:
df2.rename(columns={'List 0':'0','List 1':'1','List 2':'2','List 3':'3','List 4':'4','List 5':'5','List 6':'6','List 7':'7','List 8':'8','List 9':'9','List 10':'10','List 11':'11','List 12':'12','List 13':'13','List 14':'14','List 15':'15','List 16':'16','List 18':'18','List 20':'20','List 21':'21'},inplace=True)
df2 = df2[['Country Name', '0', '1', '2', '3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21']]
df2.set_index(['Country Name'], inplace= True)
df2 = df2.replace(to_replace='–', value='')
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
Country Name,,,,,,,,,,,,,,,,,,,,,
Uganda,39,73,32,19,28,17,93,89,78,82,...,78,78,0,78,87,80,47,81,62,78
Ukraine,98,97,100,96,97,93,75,42,19,56,...,26,47,0,0,,92,59,,,
United Arab Emirates,100,100,100,100,100,100,99,99,99,99,...,99,99,92,99,,,,,,
United Kingdom,100,100,100,99,99,99,,98,94,94,...,0,94,90,92,,,,,,
United Republic of Tanzania,50,79,37,24,37,17,99,99,97,93,...,97,97,96,96,90,55,45,50,54,66

* Now that we have the two data frames we share concatinate them together to one data frame.
* this hence will be our final data frame that we shall write to a csv file

In [127]:
frames = [df1, df2]
result = pd.concat(frames)
result

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,63,89,53,39,56,33,74,73,65,60,...,65,65,0,65,65,62,46,63,5,26
Albania,91,93,90,98,98,97,99,99,98,98,...,98,98,0,98,92,70,54,71,,
Algeria,93,95,89,87,90,82,99,96,91,91,...,91,91,0,61,92,66,25,,,
Andorra,100,100,100,100,100,100,,99,98,98,...,94,98,0,92,,,,,,
Angola,41,63,23,39,62,21,58,79,64,66,...,64,64,53,58,78,49,43,51,22,31
Anguilla,98,98,,97,97,,,,,,...,,,,,,,,,,
Antigua and Barbuda,97,,,88,,,,99,99,86,...,99,99,0,0,,,,,,
Argentina,100,100,100,95,95,94,92,97,92,87,...,92,92,75,82,,94,18,,,
Armenia,99,99,99,92,96,83,99,97,94,96,...,94,94,94,94,,57,37,71,,
Australia,100,100,100,100,,,,98,94,94,...,94,94,87,94,,,,,,
Austria,100,100,100,100,100,100,,99,87,87,...,87,87,61,0,,,,,,
Azerbaijan,84,95,72,89,92,87,98,98,97,98,...,97,97,0,97,,36,11,,1,
Bahamas,98,,,92,,,,95,94,94,...,94,94,0,94,100,,,,,
Bahrain,100,,,100,,,,99,99,99,...,99,99,98,99,98,,,,,
Bangladesh,97,98,97,47,54,43,99,99,97,97,...,97,97,0,97,97,42,77,55,,
Barbados,98,,,96,,,,99,97,97,...,97,97,0,96,,,,,,
Belarus,98,98,99,94,94,95,98,99,98,98,...,96,11,0,0,,93,45,,,
Belgium,100,100,100,99,99,99,,99,98,98,...,97,97,87,94,,,,,,
Belize,97,99,96,87,91,84,94,98,95,96,...,95,95,0,0,91,67,55,71,,
Benin,67,77,60,14,25,5,96,86,82,78,...,82,82,0,75,85,23,25,44,73,77
Bhutan,98,97,98,63,72,57,99,99,98,97,...,98,98,0,0,89,74,61,,,
Bolivia (Plurinational State of),93,99,79,53,64,27,99,99,99,99,...,99,99,99,97,87,62,22,,,
Bosnia and Herzegovina,98,97,98,95,99,92,97,90,78,79,...,78,69,0,0,,87,36,,,
Botswana,79,95,58,60,75,39,98,98,95,96,...,95,95,95,95,92,14,43,75,31,53
Brazil,97,99,87,86,91,58,99,89,86,98,...,86,86,94,94,93,50,,,,
British Virgin Islands,100,,,97,,,,,,,...,,,,,,,,,,
Brunei Darussalam,100,100,99,96,96,97,99,99,99,99,...,99,99,0,0,95,,,,,
Bulgaria,99,99,99,86,87,84,96,94,92,92,...,91,92,0,90,,,,,,
Burkina Faso,54,79,43,23,48,12,98,95,91,91,...,91,91,91,91,92,52,40,61,75,90
Burundi,56,88,52,50,46,51,93,97,94,94,...,94,94,96,94,85,63,36,69,40,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sweden,100,100,100,99,99,100,26,99,98,98,...,67,98,0,97,,,,,,
Switzerland,100,100,100,100,100,100,,99,97,97,...,0,97,0,81,,,,,,
Syrian Arab Republic,97,99,94,93,96,89,66,61,42,48,...,50,42,0,0,91,77,50,,,
Tajikistan,74,92,68,95,94,96,98,98,96,97,...,97,97,96,0,,63,60,57,1,2
Thailand,98,99,97,95,94,96,99,99,99,99,...,99,0,0,0,95,80,73,76,,
The former Yugoslav Republic of Macedonia,97,96,98,91,97,83,99,97,95,95,...,94,94,0,0,,93,62,,,
Timor-Leste,70,91,60,44,73,30,85,95,85,83,...,85,85,0,0,81,71,71,73,41,41
Togo,63,90,45,14,28,5,79,93,89,89,...,89,89,90,89,83,49,19,58,43,65
Tokelau,100,,100,93,,93,,,,,...,,,,,,,,,,
Tonga,100,100,100,93,97,92,80,83,78,80,...,78,78,0,0,,,,64,,
Trinidad and Tobago,97,,,92,,,,97,97,84,...,97,97,0,91,,74,,,,
Tunisia,94,100,83,93,98,83,95,99,98,98,...,98,98,0,0,96,60,65,,,
Turkey,99,99,100,96,99,89,96,99,98,98,...,98,98,0,98,90,,,,,
Turkmenistan,94,91,98,97,94,99,98,99,98,98,...,98,98,0,0,,59,47,,,
Turks and Caicos Islands,94,,,88,,,,,,,...,,,,,,,,,,
Tuvalu,99,100,99,91,92,91,98,99,94,94,...,94,94,0,0,,,44,79,,
Uganda,39,73,32,19,28,17,93,89,78,82,...,78,78,0,78,87,80,47,81,62,78
Ukraine,98,97,100,96,97,93,75,42,19,56,...,26,47,0,0,,92,59,,,
United Arab Emirates,100,100,100,100,100,100,99,99,99,99,...,99,99,92,99,,,,,,
United Kingdom,100,100,100,99,99,99,,98,94,94,...,0,94,90,92,,,,,,
United Republic of Tanzania,50,79,37,24,37,17,99,99,97,93,...,97,97,96,96,90,55,45,50,54,66
United States,99,100,97,100,100,100,,97,95,94,...,93,93,73,93,,,,,,
Uruguay,99,100,94,96,96,95,98,97,95,95,...,95,95,0,94,,91,,,,
Uzbekistan,,99,,100,100,100,99,99,99,99,...,99,99,99,99,,68,28,,,
Vanuatu,91,99,87,53,61,51,73,75,64,65,...,64,64,0,0,78,72,48,57,51,83
Venezuela (Bolivarian Republic of),97,99,86,95,98,72,99,98,84,82,...,84,84,47,77,5,72,38,,,
Viet Nam,91,92,91,78,91,72,95,96,96,95,...,96,96,0,0,94,81,51,,9,10
Yemen,70,85,63,60,90,44,73,76,71,65,...,71,71,59,71,70,34,25,33,,
Zambia,61,86,44,31,49,19,99,99,91,87,...,91,91,90,90,85,70,64,75,41,68
Zimbabwe,67,94,54,39,54,31,95,94,90,90,...,90,90,91,90,80,51,41,50,9,48

In [128]:
result.to_csv('./health.csv')